import { makeLesson } from "../../engine/makeLesson.js";

/* Lesson 1 · Q3 2026 · 1 and 2 Corinthians
   Authored from the official quarterly, then adapted for this engine.
   Generated by scripts/build-lessons.mjs. Edit the draft, not this file. */
export default makeLesson(
{
  "number": 1,
  "slug": "no-temas-sigue-hablando",
  "title": "Do Not Be Afraid. Keep Speaking.",
  "subtitle": "Where has God placed you, and what is silencing you there?",
  "kitName": "My Commission",
  "artifactNoun": "commission",
  "motif": "carta",
  "stages": [
    "blanco",
    "tinta",
    "renglones",
    "firma",
    "sello"
  ],
  "stageLabels": [
    "Blank page · fear",
    "First line · calling",
    "Growing lines · city",
    "Signature below · courage",
    "Sealed letter · sent"
  ],
  "verseRef": "Acts 18:9-10",
  "verseText": "Do not be afraid. Keep speaking and do not be silent, for I am with you, and no one will attack and harm you, because I have many people in this city.",
  "promise": "In a few minutes you will write your Commission, {name}: you will name the ground where God has already placed you, recognize the One who sent you, face the fear that silences you, and hold on to a promise spoken in the night. Piece by piece, the blank page will become a letter bearing your signature.",
  "ui": {
    "start": "Begin writing my commission",
    "emptyKit": "Your commission",
    "building": "Each answer adds a line",
    "buildingHint": "Tap the waiting piece. You will see the blank sheet become a sealed letter.",
    "lastPiece": "a piece is missing",
    "patternLabel": "What your letter is saying",
    "doneTitle": "Your commission is written",
    "doneSub": "You wrote it, with God. Open it, save it, share it.",
    "open": "Open my commission",
    "back": "Return to my commission",
    "kitName": "My Commission"
  },
  "slots": [
    {
      "id": "oficio",
      "n": 1,
      "label": "My work and my calling",
      "teaser": "Where do I really spend my hours…",
      "icon": "hand"
    },
    {
      "id": "llamado",
      "n": 2,
      "label": "My calling",
      "teaser": "What God would write next to my name...",
      "icon": "scroll"
    },
    {
      "id": "lugar",
      "n": 3,
      "label": "My Corinth",
      "teaser": "The specific place where I am already...",
      "icon": "map"
    },
    {
      "id": "ciudad",
      "n": 4,
      "label": "The pressure of my city",
      "teaser": "What I will face without fear...",
      "icon": "people"
    },
    {
      "id": "miedo",
      "n": 5,
      "label": "The fear that I confess",
      "teaser": "With weakness, fear and trembling...",
      "icon": "shield"
    },
    {
      "id": "promesa",
      "n": 6,
      "label": "The promise that sustains me",
      "teaser": "What he said that night...",
      "icon": "anchor"
    },
    {
      "id": "voz",
      "n": 7,
      "label": "My voice that will not be silent",
      "teaser": "What had been silencing me...",
      "icon": "voice"
    },
    {
      "id": "paso",
      "n": 8,
      "label": "My step this week",
      "teaser": "A specific step and a person…",
      "icon": "path"
    }
  ],
  "stations": [
    {
      "id": "oficio",
      "day": "Saturday · Tents and souls",
      "tag": "Piece 1 · My work and my calling",
      "title": "Your work pays the bills; your calling gives it meaning",
      "story": "William Carey repaired shoes to pay his expenses, but he said his real occupation was winning souls. Paul stitched tent canvas in Corinth (Acts 18:1-3). The needle supplied his daily bread; his words carried Christ. He did not live two separate lives. He had a trade and a calling, and the trade opened doors for the calling.",
      "cue": "Before you continue, {name}, look at where you spend your hours.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "Where do you spend most of your waking hours?",
        "hint": "Choose the real place, not the ideal",
        "saveLabel": "Save to my commission",
        "seedSub": "your land",
        "closing": "None of those places are a detour. Paul did not ask for another workshop: he turned the one he had into his first preaching room.",
        "options": [
          {
            "id": "trabajo",
            "label": "At my job, among people who don't believe",
            "insight": "That is your workshop. Paul did not complain about his workplace; he used it as a door. Where you earn a living, you have also been sent.",
            "tags": [
              "theme:mission",
              "posture:seeking",
              "tone:resolute"
            ]
          },
          {
            "id": "casa",
            "label": "At home, taking care of mine",
            "insight": "Crispus believed “with his entire house” (Acts 18:8). Homes were the first ground of the gospel, and continue to be.",
            "tags": [
              "theme:service",
              "theme:love",
              "tone:tender"
            ]
          },
          {
            "id": "estudio",
            "label": "In a classroom, studying or teaching",
            "insight": "Paul argued in the Areopagus with mocking philosophers (Acts 17:32). Difficult questions are not enemies of faith.",
            "tags": [
              "theme:truth",
              "posture:seeking",
              "tone:resolute"
            ]
          },
          {
            "id": "calle",
            "label": "Moving from place to place, with no fixed base",
            "insight": "Paul spoke in the synagogue, the marketplace, and the Areopagus (Acts 17:17). What looks scattered to you may look like reach to God.",
            "tags": [
              "theme:mission",
              "posture:seeking",
              "tone:raw"
            ]
          },
          {
            "id": "solo",
            "label": "Almost always alone",
            "insight": "Paul waited alone in Athens for Silas and Timothy, and that waiting became deeply fruitful. Loneliness does not cancel your commission.",
            "tags": [
              "react:withdraw",
              "theme:self",
              "tone:raw"
            ]
          },
          {
            "id": "iglesia",
            "label": "Among believers, almost always",
            "insight": "It is a good place, but Corinth was not confined to the synagogue. Ask God which door outside the church he wants you to walk through.",
            "tags": [
              "theme:unity",
              "posture:clinging",
              "tone:tender"
            ]
          }
        ]
      }
    },
    {
      "id": "llamado",
      "day": "Sunday · Apostle by the will of God",
      "tag": "Part 2 · My calling",
      "title": "Called, not self-appointed",
      "story": "Paul opens almost every letter in the same way: “called to be an apostle of Jesus Christ by the will of God” (1 Cor. 1:1). No human being gave him that calling (Gal. 1:1). Like Jeremiah, God set him apart from his mother's womb (Gal. 1:15; Jer. 1:5). Knowing who you are before God is what steadies you when the city shouts something different.",
      "cue": "{name}, your commission has a Sender. You did not invent it.",
      "module": {
        "type": "choiceInsight",
        "privacy": false,
        "prompt": "If God wrote your name on an assignment today, what would he say next?",
        "hint": "Choose what resonates the most, even if it's too big for you.",
        "saveLabel": "Save to my commission",
        "seedSub": "your calling",
        "closing": "Paul was called to be an apostle; the Corinthians were called to be faithful where they were. No commission from God is second class.",
        "options": [
          {
            "id": "puente",
            "label": "Be a bridge for those who never enter a church",
            "insight": "That was Paul's instinct in the market and in the Areopagus: to go where the people were already, instead of waiting for them to arrive.",
            "tags": [
              "theme:mission",
              "posture:seeking",
              "tone:resolute"
            ]
          },
          {
            "id": "consuelo",
            "label": "Accompany those who are broken",
            "insight": "Paul wrote to Corinth “with many tears” (2 Cor. 2:4). Consolation is not a minor ministry: it is the very heart of the letter.",
            "tags": [
              "theme:love",
              "posture:humble",
              "tone:tender"
            ]
          },
          {
            "id": "ensenar",
            "label": "Teach the Word clearly",
            "insight": "Paul stayed for a year and a half “teaching the word of God” (Acts 18:11). Teaching is sowing slowly, and that seed does not return empty.",
            "tags": [
              "theme:word",
              "posture:seeking",
              "tone:resolute"
            ]
          },
          {
            "id": "hogar",
            "label": "Sustain a home where Christ is seen",
            "insight": "Aquila and Priscilla sewed tents and hosted the apostle. Their home became a theology school that smelled like a workshop.",
            "tags": [
              "theme:service",
              "theme:love",
              "tone:tender"
            ]
          },
          {
            "id": "manos",
            "label": "Serve with your hands, without speeches",
            "insight": "Before Paul said a word in Corinth, he had already worked side by side with those people. The hands also preach.",
            "tags": [
              "theme:service",
              "posture:humble",
              "tone:resolute"
            ]
          },
          {
            "id": "sinsaber",
            "label": "I don't know yet, and that weighs on me",
            "insight": "The fact that it weighs on you shows that you are seeking it. God does not hide your calling from you. He usually reveals it while you walk, not before you begin.",
            "tags": [
              "react:doubt",
              "theme:hope",
              "posture:seeking"
            ]
          }
        ]
      }
    },
    {
      "id": "lugar",
      "day": "Monday · From Athens to Corinth",
      "tag": "Piece 3 · My Corinth",
      "title": "In the synagogue, in the square and in the Areopagus",
      "story": "Paul reached Athens by a roundabout route while fleeing opposition in Berea. As he waited for Silas and Timothy, he did not sit still: he spoke in the synagogue, the marketplace, and the Areopagus (Acts 17:16-34). Then he went down to Corinth and stayed for a year and a half. He never waited for the perfect setting. He used the one in front of him.",
      "cue": "Look closely at the map, {name}: you are already in your Corinth.",
      "module": {
        "type": "pickReveal",
        "saveLabel": "Save to my commission",
        "seedSub": "your Corinth",
        "prompt": "Which of these places is your Corinth today?",
        "hint": "Touch each one and stay with the one that most resembles your week",
        "chooseLabel": "God put me here",
        "closing": "Paul chose Corinth for its location, not for its convenience. Ellen White puts it bluntly: from there the gospel “would be easily communicated to all parts of the world” (Sketches from the Life of Paul, p. 99). Your place also has exits.",
        "allowCustom": {
          "label": "write mine",
          "placeholder": "The place where I spend my days is…",
          "extraKey": "corintoPropio"
        },
        "items": [
          {
            "t": "My work, where no one talks about God",
            "ref": "Hech. 18:3",
            "meaning": "Paul sewed tents with Aquila and Priscilla. The workshop was his first preaching room, and his work gave him credibility before he ever made an argument."
          },
          {
            "t": "The market, the street, the line, transportation",
            "ref": "Hech. 17:17",
            "meaning": "\"He argued in the square every day with those who attended.\" Nothing informal is too small for God to use."
          },
          {
            "t": "My family, who still doesn't believe",
            "ref": "Hech. 18:8",
            "meaning": "Crispus, head of the synagogue, believed \"with his entire house.\" God knows how to convert entire homes, and it almost always starts with just one."
          },
          {
            "t": "A hostile place where they already rejected me",
            "ref": "Hech. 18:6",
            "meaning": "\"They opposed and blasphemed.\" Paul dusted off his clothes, crossed to the next house and continued talking. The rejection changed his method, not his assignment."
          }
        ]
      }
    },
    {
      "id": "ciudad",
      "day": "Tuesday · The city of Corinth",
      "tag": "Piece 4 · The pressure of my city",
      "title": "Two ports, many idols, a lot of noise",
      "story": "Corinth was rich, cosmopolitan and brash: two ports that moved the world's commerce, temples to Apollo, Athena and Aphrodite, and a morality that would sound very familiar to us today (1 Cor. 5:9-11; 8:5). Paul didn't land there by accident: he chose that city on purpose. What intimidates you about your environment, God sees as a crossroads.",
      "cue": "Your city is not an accident, {name}.",
      "module": {
        "type": "skillThenCommit",
        "saveLabel": "Save to my commission",
        "seedSub": "your city",
        "skill": {
          "prompt": "Train your eye: a door that God opens, or a lie that silences you?",
          "hint": "What seems like an obstacle is usually access",
          "badge": "You are learning to read your city as Paul read it",
          "cats": [
            "Door that God opens",
            "Lie that silences me"
          ],
          "rounds": [
            {
              "t": "\"People from all over come here, all the time.\"",
              "a": 0,
              "fb": "Door that God opens: that is why Paul chose Corinth. Whatever he planted there would travel by boat to the end of the known world."
            },
            {
              "t": "“No one here will believe; speaking would be a waste of time.”",
              "a": 1,
              "fb": "A lie that will keep you silent: “I have many people in this city” (Acts 18:10) was spoken in the most unlikely place. God told Paul what he could not yet see."
            },
            {
              "t": "\"My job places me every day alongside people who would never enter a church.\"",
              "a": 0,
              "fb": "Door that God opens: Aquila, Priscilla and Paul shared a workshop, table and faith (Acts 18:2-3). Work was the bridge."
            },
            {
              "t": "“They rejected me once; I had better stay silent forever.”",
              "a": 1,
              "fb": "A lie that silences you: Paul was insulted in the synagogue and the next day he was teaching in the house next door (Acts 18:6-7)."
            },
            {
              "t": "\"Idolatry and immorality are everywhere here.\"",
              "a": 0,
              "fb": "Door that God opens: that is precisely why he stayed for a year and a half. Where darkness abounds, more light is needed, not less."
            },
            {
              "t": "\"I am one against an entire city.\"",
              "a": 1,
              "fb": "A lie that silences you: you were never alone. \"I am with you, and no one can harm you\" (Acts 18:10)."
            }
          ],
          "summary": "The same city Paul considered “a very questionable field of work” became home to a large church. The difference was not the city; it was his decision to stay."
        },
        "commit": {
          "prompt": "What pressure from your environment are you going to face with the gospel and not with fear?",
          "hint": "Name it specifically. What is not named, continues to rule.",
          "placeholder": "mockery, indifference, the fashion of keeping quiet...",
          "extraKey": "presionCiudad",
          "options": [
            "The mockery of those who already know what I believe",
            "The total indifference of those around me",
            "The moral environment where I work or study",
            "The pressure to fit in and not make anyone uncomfortable",
            "The feeling of being a minority everywhere"
          ]
        }
      }
    },
    {
      "id": "miedo",
      "day": "Wednesday Fear and trembling in Corinth",
      "tag": "Piece 5 · The fear I confess",
      "title": "With weakness, and much fear and trembling",
      "story": "Paul himself confessed in writing that he arrived in Corinth “in weakness, and much fear and trembling” (1 Cor. 2:3). He was already planning his exit, as he had done in Berea. Then, at night, the Lord appeared to him: “Do not be afraid. Keep speaking and do not be silent” (Acts 18:9). He did not scold Paul for being afraid. He gave him his presence and a gentle command: continue.",
      "cue": "The truth about fear is told here, {name}.",
      "module": {
        "type": "perspectiveFlip",
        "saveLabel": "Save to my commission",
        "seedSub": "your fear",
        "prompt": "Touch each card to see your fear as God sees it",
        "hint": "Two readings from the same night",
        "pairs": [
          {
            "see": "You see a city too hard for the gospel.",
            "sees": "He sees “many people in this city” (Acts 18:10): people who do not yet know that they are his."
          },
          {
            "see": "You feel that your fear disqualifies you.",
            "sees": "Paul preached while trembling and wrote it down. Fear does not cancel the commission; it simply makes us need God's presence."
          },
          {
            "see": "You think your voice is too small to change anything.",
            "sees": "\"My word that goes out of my mouth will not return to me void\" (Isa. 55:11). The seed does not depend on the size of the hand."
          },
          {
            "see": "You think that if you retire, no one will notice.",
            "sees": "God interrupted Paul's departure with a vision. Your permanence matters more to him than you imagine."
          }
        ],
        "chooseLabel": "This is the truth I needed to hear",
        "teach": "Notice the order of the vision: first “do not be afraid,” then “keep talking.” God does not wait for your fear to go away before giving you the task. He gives you his presence within fear, and that is enough.",
        "commit": {
          "prompt": "Write in plain words the fear that has silenced you most",
          "hint": "Naming it before God is already starting to speak",
          "placeholder": "What makes me silent is…",
          "extraKey": "miedoNombrado"
        }
      }
    },
    {
      "id": "promesa",
      "day": "Wednesday · I am with you",
      "tag": "Piece 6 · The promise that sustains me",
      "title": "Four nails for a long night",
      "story": "The vision that night held four firm truths: do not be afraid, keep speaking, I am with you, and I have many people here. It echoes Isaiah 41:10: “Do not fear, for I am with you. I will strengthen you, help you, and uphold you.” Paul understood that God was telling him to stay, and he remained for a year and six months.",
      "cue": "{name}, hold on to this when your voice shakes.",
      "module": {
        "type": "anchorChain",
        "saveLabel": "Save to my commission",
        "seedSub": "your promise",
        "prompt": "Which of these words are you going to hold this week?",
        "hint": "Choose the one you need most on Monday morning",
        "options": [
          "That my fear does not disqualify me",
          "That I must continue speaking even if I tremble",
          "That he is with me even when I do not feel it",
          "There are already people waiting for what I have to say",
          "That staying is an order, not a punishment"
        ],
        "allowCustom": {
          "placeholder": "I'm going to hold on to that...",
          "extraKey": "promesaPropia"
        },
        "chain": [
          {
            "word": "Don't be afraid",
            "line": "Fear was not Paul's sin; it was the starting point of the promise."
          },
          {
            "word": "Keep talking and don't shut up",
            "line": "Hostility did not cancel the commission. It only confirmed it more strongly."
          },
          {
            "word": "I am with you",
            "line": "You never preached alone, although you have felt that way many times."
          },
          {
            "word": "I have many people in this city",
            "line": "God already knows those who do not yet believe. Your task is to speak; the results belong to him."
          }
        ],
        "climax": "The chain is complete."
      }
    },
    {
      "id": "voz",
      "day": "Thursday · The letters to the Corinthians",
      "tag": "Piece 7 · My voice that does not remain silent",
      "title": "He wrote crying, and did not leave",
      "story": "Bad news came from Ephesus through Chloe's family: divisions, strife, immorality (1 Cor. 1:11). Paul could have let them go and found a healthier church. Instead he wrote, and he wrote “with many tears” (2 Cor. 2:4), not to hurt them but so they would know how much he loved them. A troubled church received some of the richest pages in the New Testament because someone refused to keep quiet.",
      "cue": "There is something that is keeping you quiet, {name}. Name it.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "What has been keeping you quiet lately?",
        "hint": "Be honest. Nobody is evaluating you here.",
        "saveLabel": "Save to my commission",
        "seedSub": "your silence",
        "closing": "Paul did not speak because he had an answer for everything. He resolved “to know nothing among you except Jesus Christ and him crucified” (1 Cor. 2:2). Your voice does not need to be brilliant. It needs to be faithful to the cross.",
        "options": [
          {
            "id": "ridiculo",
            "label": "The fear of making a fool of myself",
            "insight": "At the Areopagus they mocked Paul to his face (Acts 17:32), yet some believed. Mockery has never been the last word.",
            "tags": [
              "react:fear",
              "posture:avoidant",
              "tone:raw"
            ]
          },
          {
            "id": "rechazo",
            "label": "Being rejected by people I love",
            "insight": "It is the most expensive fear of all, because it does hurt there. But Paul wrote to those who could reject him, calling them “beloved children” (1 Cor. 4:14).",
            "tags": [
              "react:fear",
              "theme:relationship",
              "tone:tender"
            ]
          },
          {
            "id": "indigno",
            "label": "Feeling that my life does not set an example",
            "insight": "Paul called himself “the least of the apostles” (1 Cor. 15:9) and continued to preach. The grace that saved you is exactly the message you carry.",
            "tags": [
              "theme:humility",
              "posture:humble",
              "tone:raw"
            ]
          },
          {
            "id": "cansancio",
            "label": "Fatigue: I already tried it and nothing happened",
            "insight": "In the synagogue at Corinth, Paul also felt that he was not measuring up. Then Crispus was baptized, and many more followed (Acts 18:8).",
            "tags": [
              "react:apathy",
              "theme:hope",
              "tone:raw"
            ]
          },
          {
            "id": "conflicto",
            "label": "I don't want conflict with anyone",
            "insight": "The peace that is only achieved by silence is not peace: it is distance. Paul preferred an uncomfortable letter rather than a comfortable silence.",
            "tags": [
              "react:withdraw",
              "posture:avoidant",
              "tone:tender"
            ]
          },
          {
            "id": "razon",
            "label": "Wanting to be right before loving",
            "insight": "One can remain silent out of fear and also because of wounded pride. Paul wrote weeping, not winning arguments (2 Cor. 2:4).",
            "tags": [
              "react:pride",
              "posture:proud",
              "theme:love"
            ]
          }
        ]
      }
    },
    {
      "id": "paso",
      "day": "Friday · To study and meditate",
      "tag": "Piece 8 · My step this week",
      "title": "He decided to stay",
      "story": "Ellen White relates that Paul considered Corinth “a very questionable field of work” and was determined to abandon it. After the night vision, \"he understood that it was an order to remain in Corinth\" (Sketches from the Life of Paul, pp. 106, 107). He stayed, made the city his headquarters, and several churches were born from there. It all started with one night and a decision.",
      "cue": "Close your commission, {name}, with something you can do tomorrow.",
      "module": {
        "type": "commitDuo",
        "saveLabel": "Seal my commission",
        "seedSub": "your step",
        "stepPrompt": "My specific step this week",
        "stepHint": "Tap an idea or write your own",
        "stepOptions": [
          "Talk about Jesus with a specific person",
          "Stay where I wanted to go, and serve one more month",
          "Pray every morning for three people at my work",
          "Write a message of encouragement to someone who walked away",
          "Say out loud what I have been keeping silent for fear"
        ],
        "stepPlaceholder": "my specific step...",
        "stepExtraKey": "pasoTexto",
        "personPrompt": "A person from my Corinth that I am going to start with",
        "personHint": "Who would you talk to first if you knew God was already waiting for you?",
        "personPlaceholder": "a name...",
        "personExtraKey": "personaCorinto"
      }
    }
  ],
  "encourage": [
    "“Do not be afraid. Keep talking and don't be silent, because I am with you, and no one can harm you.” (Acts 18:9-10)",
    "“I have many people in this city.” (Acts 18:10)",
    "“Do not be afraid, for I am with you; do not faint, for I am your God who strengthens you.” (Isa. 41:10)",
    "“My word that comes out of my mouth will not return to me void.” (Isa. 55:11)",
    "“I resolved to know nothing among you except Jesus Christ, and him crucified.” (1 Cor. 2:2)",
    "“I wrote to you with many tears, so that you would know how much more I love you.” (2 Cor. 2:4)"
  ],
  "discussion": [
    "Paul was convinced that his calling came from God and not from men. Why does the way you serve change so much when you know for sure who sent you?",
    "For a moment Paul wanted to leave Corinth and go away. What made you change your mind, and how does that help us when we want to abandon something God gave us? Will there be legitimate occasions to leave?",
    "The believers in Corinth were greatly influenced by the culture that surrounded them, and that is also true for us today. How can you be in the world (John 17:11, 15) without allowing yourself to be shaped by “the lust of the flesh, the lust of the eyes, and the pride of life” (1 John 2:16)?",
    "Paul made tents to live and won people for Christ as a true occupation. What does that double reality look like in your specific week, and what would have to change for your craft to serve your purpose?"
  ],
  "facilitator": [
    {
      "stationId": "oficio",
      "apertura": "William Carey repaired shoes, but said his real occupation was winning souls. What would you say is your real occupation?",
      "seguimiento": "Where do you really spend most of your waking hours during the week?",
      "ilustracion": "Paul sewed tent canvas with Aquila and Priscilla (Acts 18:1-3). The workshop paid for bread and opened conversations.",
      "transicion": "If your work supports the commission, it matters where that commission comes from.",
      "actividad": "Invite each person to say in one sentence where they spend their hours and whom they see there each day.",
      "cierre": "Lord, take our ordinary office and make it a door for your gospel.",
      "notas": "Take care that no one feels that their work is less spiritual than that of others."
    },
    {
      "stationId": "llamado",
      "apertura": "Why does Paul insist on opening almost all of his letters by saying that he is an apostle “by the will of God” (1 Cor. 1:1)?",
      "seguimiento": "How do you know that your calling comes from God and not from the expectations of others?",
      "ilustracion": "Like Jeremiah, God set Paul apart before he was born (Gal. 1:15; Jer. 1:5). The call precedes the résumé.",
      "transicion": "A commission with a Sender needs a destination. Let us see where God placed Paul, and where he has placed us.",
      "actividad": "Compare 1 Corinthians 1:1, Romans 1:1, and Galatians 1:1 and note which two things Paul always highlights.",
      "cierre": "Thank you, Lord, because we do not name ourselves: you called us first.",
      "notas": "Someone will say they don't know their calling. Treat it as a good starting point, not a failure."
    },
    {
      "stationId": "lugar",
      "apertura": "Paul arrived in Athens fleeing the opposition in Berea. What did he do while waiting for Silas and Timothy?",
      "seguimiento": "What is your specific Corinth this week, the place where you are already and haven't quite chosen?",
      "ilustracion": "Synagogue, market and Areopagus: three different audiences, a single message. Paul did not wait for the perfect scenario.",
      "transicion": "That place has a culture, and that culture applies pressure. Let's look at what Corinth was like.",
      "actividad": "Read Acts 17:16-34 and 18:1-11 and make a list of all the places where Paul spoke.",
      "cierre": "Open our eyes, Lord, to see opportunities where we only saw routine.",
      "notas": "It helps to make the answers concrete: a building, an office, a house, not general ideas."
    },
    {
      "stationId": "ciudad",
      "apertura": "Corinth had two ports, temples to half a dozen gods and a terrible moral reputation. Why would Paul choose that city?",
      "seguimiento": "What pressure from our culture makes it more difficult to talk about the gospel today?",
      "ilustracion": "Ellen White says that from Corinth the gospel “would be easily communicated to all parts of the world” (Sketches from the Life of Paul, p. 99).",
      "transicion": "Even with the city's strategic advantages, Paul was afraid. Let's hear his confession.",
      "actividad": "Classify several phrases together: door that God opens or lie that silences us?",
      "cierre": "Give us eyes to read our city as a field, not as an enemy.",
      "notas": "Avoid turning this into a general complaint about society. Redirect to opportunity."
    },
    {
      "stationId": "miedo",
      "apertura": "Paul admits that he was in Corinth “in weakness, and much fear, and trembling” (1 Cor. 2:3). Does that confession surprise you?",
      "seguimiento": "What specific fear has kept you silent in the last month?",
      "ilustracion": "God did not remove his fear before giving him the order. First he said \"don't be afraid,\" then \"keep talking.\"",
      "transicion": "Against that fear, God put four words. Let's go over them one by one.",
      "actividad": "Read Acts 18:9-10 and Isaiah 41:10 aloud and compare the promises.",
      "cierre": "Lord, do not take away our calling because we are afraid; give us your presence in the midst of fear.",
      "notas": "This is the most vulnerable moment of the lesson. Don't pressure anyone to share."
    },
    {
      "stationId": "promesa",
      "apertura": "The vision had four parts. Which of them do you find the most difficult to believe?",
      "seguimiento": "What does it mean to you that God says \"I have many people\" in the place where you don't see anyone?",
      "ilustracion": "Paul stayed for a year and six months. The promise did not take away his work; it took away his urge to flee.",
      "transicion": "Sustained by that promise, Paul did something remarkable: he wrote instead of walking away.",
      "actividad": "Let each person choose one of the four phrases and explain why that one and not another.",
      "cierre": "Uphold us, Lord, with your righteous right hand when our voices tremble.",
      "notas": "He emphasizes that the promise did not promise ease, but rather company and fruit."
    },
    {
      "stationId": "voz",
      "apertura": "Upon learning of the divisions in Corinth, Paul could have let the church go. Why did he write instead of giving up?",
      "seguimiento": "Who are you about to let go, and what would happen if you wrote to them instead?",
      "ilustracion": "“I wrote to you with many tears” (2 Cor. 2:4). The correction born of love is noticeable in the tone.",
      "transicion": "From the voice that refuses silence, we move to a concrete step for the next few days.",
      "actividad": "Read 2 Corinthians 2:4 and talk about the difference between correcting to hurt and correcting to love.",
      "cierre": "Teach us to speak with tears rather than with harshness.",
      "notas": "Moderate if someone uses the topic to justify harsh criticism of the local church."
    },
    {
      "stationId": "paso",
      "apertura": "What would have happened to Corinth if Paul had obeyed his first impulse to leave?",
      "seguimiento": "Is there something God is asking you to hold on to a little longer before you give up?",
      "ilustracion": "Paul made Corinth his headquarters and several churches were born from there (Sketches from the Life of Paul, p. 109).",
      "transicion": "Let's close with a specific step and a named person.",
      "actividad": "Each one shares a step for this week and the name of someone they will pray for.",
      "cierre": "Give us the courage to stay and the tenderness to continue talking.",
      "notas": "Write down the names and ask about them next week."
    }
  ],
  "patternTemplate": "{name}, you named where your hours go: “{slot:oficio}”. Right there, without changing course, God gave you this calling: “{slot:llamado}”. You pointed to your Corinth: “{slot:lugar}”. Then you confessed what had been silencing you: “{slot:voz}”. The page is no longer blank. It has lines, and it has a Sender.",
  "outOracion": "Lord, you know where my hours go: “{slot:oficio}”. I often feel small there. Thank you that I did not appoint myself; this is the calling I heard: “{slot:llamado}”. I name what silences me: “{slot:voz}”. I name my Corinth: “{slot:lugar}”. This week I want to face “{slot:ciudad}” without fear. I hold on to this promise: “{slot:promesa}”. Help me not to be silent, because you said: “{verse}” ({verseRef}). In the name of Jesus, amen.",
  "outAliento": "{name}, you are not standing alone against an entire city. Paul arrived in Corinth trembling and ready to leave, and God did not scold him. God gave him his presence and a gentle command. You named what silences you: “{slot:voz}”. You also chose this promise: “{slot:promesa}”. Keep speaking. People are already waiting in the place where you think no one is listening.",
  "outAccion24": "In the next 24 hours I am going to {slot:paso|lower}, right where God already placed me: {slot:lugar|lower}.",
  "outPregunta": "This week I named what had been silencing me: “{slot:voz}”. I also discovered that God already has people waiting in my Corinth: “{slot:lugar}”. Where has God placed you, and what is silencing you there?",
  "outTarjeta": "My commission this week: God placed me in {slot:lugar|lower}, called me to {slot:llamado|lower}, and asked me not to be silent even when I tremble.\nVerse: “{verse}” ({verseRef})."
}
);
