import { makeLesson } from "../../engine/makeLesson.js";

/* Lesson 10 · Q3 2026 · 1 and 2 Corinthians
   Authored from the official quarterly, then adapted for this engine.
   Generated by scripts/build-lessons.mjs. Edit the draft, not this file. */
export default makeLesson(
{
  "number": 10,
  "slug": "tesoro-en-barro",
  "title": "Treasure in Clay",
  "subtitle": "What if the crack you hide is exactly where the light escapes?",
  "kitName": "My Clay Vessel",
  "artifactNoun": "vessel",
  "motif": "barro",
  "forDate": "2026-09-05",
  "stages": [
    "polvo",
    "torno",
    "grieta",
    "luz",
    "gloria"
  ],
  "stageLabels": [
    "Shapeless clay · I feel useless",
    "On the wheel · I let myself be shaped",
    "The crack appears · I name it",
    "Light escapes · I serve as I am",
    "Vessel filled · an eternal weight of glory"
  ],
  "verseRef": "2 Cor. 4:8-10",
  "verseText": "We are hard pressed on every side, but not crushed; perplexed, but not in despair; persecuted, but not abandoned; struck down, but not destroyed.",
  "promise": "In a few minutes you will hold your own clay vessel, {name}: you will face the weariness you carry, name the crack that shames you, and see that this is exactly where the light escapes. Piece by piece, what you thought was useless will be filled.",
  "ui": {
    "start": "Take my clay vessel",
    "emptyKit": "Your vessel",
    "building": "Each answer adds a piece",
    "buildingHint": "Tap the waiting piece. Watch shapeless clay become a vessel filled with light.",
    "lastPiece": "One piece remains",
    "patternLabel": "Your pattern in the clay",
    "doneTitle": "Your vessel is full",
    "doneSub": "It is not a perfect vessel. It is a vessel with treasure inside. Open it, save it, and share it.",
    "open": "Open my vessel",
    "back": "Back to my vessel",
    "kitName": "My Clay Vessel"
  },
  "slots": [
    {
      "id": "barro",
      "n": 1,
      "label": "My clay today",
      "teaser": "How I arrive today, without a mask...",
      "icon": "cup"
    },
    {
      "id": "carta",
      "n": 2,
      "label": "The letter I am",
      "teaser": "What truly validates a ministry...",
      "icon": "scroll"
    },
    {
      "id": "grieta",
      "n": 3,
      "label": "My crack",
      "teaser": "What I hide, and where the light escapes...",
      "icon": "sun"
    },
    {
      "id": "peso",
      "n": 4,
      "label": "The weight I await",
      "teaser": "What is momentary beside what is eternal...",
      "icon": "crown"
    },
    {
      "id": "embajada",
      "n": 5,
      "label": "My embassy",
      "teaser": "The person to whom I carry reconciliation...",
      "icon": "voice"
    },
    {
      "id": "santidad",
      "n": 6,
      "label": "What I set apart",
      "teaser": "The space I leave for his presence...",
      "icon": "water"
    },
    {
      "id": "consuelo",
      "n": 7,
      "label": "The comfort I receive",
      "teaser": "What the God of all comfort gives me...",
      "icon": "heart"
    },
    {
      "id": "paso",
      "n": 8,
      "label": "My step this week",
      "teaser": "One concrete step and someone I will tell...",
      "icon": "path"
    }
  ],
  "stations": [
    {
      "id": "barro",
      "day": "Saturday · The authentic Christian ministry",
      "tag": "Piece 1 · My clay today",
      "title": "We have this treasure in clay vessels",
      "story": "Paul did not write this from a quiet office. He wrote after beatings and slander, exhausted by a church that caused him pain. In the middle of it all he gave the New Testament's most liberating image of service: \"We have this treasure in jars of clay to show that this all-surpassing power is from God and not from us\" (2 Cor. 4:7). Clay is not an accident in the plan. It is the plan. God is not looking for fine porcelain, but for someone honest enough that when something good emerges, no one mistakes where it came from.",
      "cue": "Before moving forward, {name}, take your vessel in your hands and look at it as it is today.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "How is the clay you're made of today?",
        "hint": "Choose the most sincere, not the most presentable",
        "saveLabel": "Save to my vessel",
        "seedSub": "Your clay",
        "options": [
          {
            "id": "agotado",
            "label": "Tired, almost without strength",
            "insight": "Paul was too: \"hard pressed on every side\" (2 Cor. 4:8). Weariness does not disqualify the vessel. It makes clear whose power sustains it.",
            "tags": [
              "theme:humility",
              "posture:humble",
              "tone:raw"
            ]
          },
          {
            "id": "inutil",
            "label": "Too broken to serve",
            "insight": "God never promised to use you despite your fragility. He promised to use you with it, so that it would be clear that the surpassing power is his (2 Cor. 4:7). You are not disqualified; God can work through the very weakness you did not choose.",
            "tags": [
              "react:withdraw",
              "theme:grace",
              "tone:tender"
            ]
          },
          {
            "id": "fingiendo",
            "label": "Whole on the outside, broken inside",
            "insight": "Maintaining a façade is more exhausting than admitting the crack. Paul stopped defending himself and began showing his scars. There he found both rest and ministry.",
            "tags": [
              "react:control",
              "theme:self",
              "posture:avoidant"
            ]
          },
          {
            "id": "presionado",
            "label": "Tight",
            "insight": "\"In trouble, but not desperate\" (2 Cor. 4:8). Look at the comma: the pressure is real, and so is the \"but.\" God may let the pressure reach your limit, but never to destroy you.",
            "tags": [
              "react:fear",
              "theme:hope",
              "posture:clinging"
            ]
          },
          {
            "id": "ocupado",
            "label": "Serving a lot, but empty inside",
            "insight": "A vessel can be used everywhere and still be empty. Before pouring out again, let God fill you. You do not manufacture the treasure; you receive it.",
            "tags": [
              "react:apathy",
              "theme:service",
              "posture:seeking"
            ]
          },
          {
            "id": "firme",
            "label": "By grace, today I am sustained",
            "insight": "Good. Keep this certainty for the day you do not feel it: what sustains you today is not your mood, but God. \"Knocked down, but not destroyed\" (2 Cor. 4:9).",
            "tags": [
              "theme:grace",
              "posture:surrendering",
              "tone:resolute"
            ]
          }
        ]
      }
    },
    {
      "id": "carta",
      "day": "Sunday · The fruits of an authentic ministry",
      "tag": "Piece 2 · The letter that I am",
      "title": "You are our letter",
      "story": "In Corinth people asked for letters of recommendation much as they ask for titles and followers today. Paul carried none. When they demanded credentials, he pointed to the people in front of him: \"You yourselves are our letter, written on our hearts\" (2 Cor. 3:2). His only endorsement was changed lives, written \"not with ink but with the Spirit of the living God\" (2 Cor. 3:3). Then he made clear where all of it came from: \"Our competence comes from God\" (2 Cor. 3:5).",
      "cue": "Think for a moment, {name}: what is your endorsement actually written on?",
      "module": {
        "type": "pickReveal",
        "saveLabel": "Save to my vessel",
        "seedSub": "Your letter",
        "prompt": "Tap every credential and find out which one really credits",
        "hint": "Touch all four and stay with the one you want to be yours",
        "chooseLabel": "This is the letter I want to be",
        "closing": "Stop looking for a paper that authorizes you. The Spirit is already writing, slowly, on hearts you may not even know about. \"The letter kills, but the Spirit gives life\" (2 Cor. 3:6).",
        "allowCustom": {
          "label": "Write mine",
          "placeholder": "I want my life to say...",
          "extraKey": "cartaPropia"
        },
        "items": [
          {
            "t": "A position, a title, a credential",
            "ref": "2 Cor. 3:1",
            "meaning": "Paul did not have letters of recommendation and was the most fruitful missionary in history. What you credit is not printed on paper."
          },
          {
            "t": "Lives changed by the Spirit",
            "ref": "2 Cor. 3:2-3",
            "meaning": "\"You are a letter from Christ, written not in ink, but with the spirit of the living God.\" The ink is the spirit; the page, a life that was previously lost."
          },
          {
            "t": "My ability and my effort",
            "ref": "2 Cor. 3:5",
            "meaning": "\"Our competition comes from God.\" If your ministry is sustained by your talent, the day that talent fails you will fall."
          },
          {
            "t": "A pact that gives life and does not condemn",
            "ref": "2 Cor. 3:6",
            "meaning": "The gospel is not put on you as a burden. \"The Spirit vivifies\": it gives you the breath that the demand had taken from you."
          }
        ]
      }
    },
    {
      "id": "grieta",
      "day": "Monday · Suffering and Glory",
      "tag": "Piece 3 My Crack",
      "title": "That's where the light comes from",
      "story": "Here is the heart of the entire quarter. Paul gives a brutal list: hard pressed, perplexed, persecuted, struck down. After each phrase he places a \"but\" that changes everything: not crushed, not in despair, not abandoned, not destroyed (2 Cor. 4:8-9). He does not deny that the wound exists. He says it does not have the final word. Then comes the turn: \"We always carry around in our body the death of Jesus, so that the life of Jesus may also be revealed in our body\" (2 Cor. 4:10). An unbroken vessel lets nothing through. A cracked one does. What you call shame, God calls a window.",
      "cue": "Breathe, {name}. No one else is going to see this, and you will not leave here condemned.",
      "module": {
        "type": "perspectiveFlip",
        "saveLabel": "Save to my vessel",
        "seedSub": "Your crack",
        "prompt": "Touch every card to see your fracture as God sees it",
        "hint": "The same, looked from the other side",
        "pairs": [
          {
            "see": "You see a crack that ruins the vessel.",
            "sees": "He sees the exact opening through which his light shines. \"This surpassing power is from God and not from us\" (2 Cor. 4:7)."
          },
          {
            "see": "You see a weakness that disqualifies you.",
            "sees": "He sees someone who will not take credit for what only God can do. Your self-reliance can hinder his work more than your fragility ever could."
          },
          {
            "see": "You see a tired body that no longer performs like before.",
            "sees": "He sees the death of Jesus carried in you \"so that his life may also be revealed in our body\" (2 Cor. 4:10). What is being spent in you becomes life for others."
          },
          {
            "see": "You see lost years and spent strength.",
            "sees": "He sees two different clocks: \"Though outwardly we are wasting away, inwardly we are being renewed day by day\" (2 Cor. 4:16)."
          }
        ],
        "chooseLabel": "This is the truth that I needed to hear",
        "teach": "Hear this slowly, because it changes how you see yourself: the gospel is carried by fragile people precisely so the glory belongs to God alone (2 Cor. 4:15). If you were flawless, people might admire the vessel. Because you are not, they can see the treasure. Your crack is not an obstacle to the plan; in God's hands it becomes part of the plan.",
        "commit": {
          "prompt": "Name the crack you are ashamed of",
          "hint": "Write it without decorating it. This is where the light will come in.",
          "placeholder": "The crack I hide is...",
          "extraKey": "grietaPropia",
          "shareable": false
        }
      }
    },
    {
      "id": "peso",
      "day": "Monday · What is not seen",
      "tag": "Piece 4 · The weight I await",
      "title": "Mild and momentary",
      "story": "Paul places two things on a scale. On one side is everything he has suffered: prisons, lashes, shipwrecks, betrayals. On the other is what is coming. He dares to call the first \"light and momentary troubles\" because they are \"achieving for us an eternal glory that far outweighs them all\" (2 Cor. 4:17). He is not minimizing pain. He is measuring it against something so weighty it cannot fit inside this life. This is why he looks where no one else looks: \"What is seen is temporary, but what is unseen is eternal\" (2 Cor. 4:18).",
      "cue": "Today it weighs, {name}, and still it is worth putting both things on the balance.",
      "module": {
        "type": "anchorChain",
        "saveLabel": "Seal in my vessel",
        "seedSub": "Your hope",
        "prompt": "What hope are you going to seal today inside your vessel?",
        "hint": "Choose the one you want to remember when you weigh again",
        "options": [
          "That this has an end date",
          "That God does not waste my pain",
          "That inside I renew myself every day",
          "That the resurrection awaits me with a new body",
          "That the eternal weighs more than what crushes me today"
        ],
        "allowCustom": {
          "placeholder": "The hope that seal is...",
          "extraKey": "esperanzaPropia"
        },
        "chain": [
          {
            "word": "My affliction is real",
            "line": "Paul never denied it. He made a very long list of what hurt him (2 Cor. 6:4-5). Faith does not demand that you pretend that you are well."
          },
          {
            "word": "My affliction is momentary",
            "line": "\"Slight momentary tribulation\" (2 Cor. 4:17). It has an end date. What seems endless today is already told by God."
          },
          {
            "word": "Is producing a weight of glory",
            "line": "It does not say affliction is merely compensated. It says it produces. God wastes nothing you are walking through."
          },
          {
            "word": "I look at what you don't see",
            "line": "\"Not by looking at the things that are seen, but those that are not seen\" (2 Cor. 4:18). By faith, not by sight, and that is why the vessel is still standing."
          }
        ],
        "climax": "The chain is complete."
      }
    },
    {
      "id": "embajada",
      "day": "Tuesday · The Ministry of Reconciliation",
      "tag": "Piece 5 · My embassy",
      "title": "We are ambassadors in the name of Christ",
      "story": "Paul did not preach to display himself. \"May I never boast except in the cross of our Lord Jesus Christ\" (Gal. 6:14). He knew that in Christ God \"reconciled us to himself\" and then \"gave us the ministry of reconciliation\" (2 Cor. 5:18). What is received is passed on: \"We are therefore Christ's ambassadors, as though God were making his appeal through us\" (2 Cor. 5:20). An ambassador does not carry a private agenda or speak in their own name. They carry a message they did not invent from the One who has already taken the first step.",
      "cue": "Ask yourself this calmly, {name}: Who is he sending you to?",
      "module": {
        "type": "choiceInsight",
        "privacy": false,
        "prompt": "If today you are an ambassador of reconciliation, where does your embassy start?",
        "hint": "Choose the one that God is putting in front of you",
        "saveLabel": "Save to my vessel",
        "seedSub": "Your embassy",
        "closing": "Do not wait until you feel worthy to go. \"Christ's love compels us\" (2 Cor. 5:14). Your virtue does not push you forward; his love does. You go as a clay vessel, which is exactly how he chooses to send you.",
        "options": [
          {
            "id": "familia",
            "label": "Someone from my house who left",
            "insight": "Reconciliation with God is almost always put to the test at the table of your own home. Start by approaching without reproach, as God approached you.",
            "tags": [
              "theme:relationship",
              "theme:love",
              "tone:tender"
            ]
          },
          {
            "id": "enemistad",
            "label": "A broken relationship that I avoid",
            "insight": "\"All this comes from God, who reconciled us\" (2 Cor. 5:18). Anyone forgiven at that price can no longer remain comfortable in hostility.",
            "tags": [
              "react:withdraw",
              "theme:unity",
              "posture:avoidant"
            ]
          },
          {
            "id": "lejano",
            "label": "Someone who doesn't know Jesus",
            "insight": "You do not bring them a religion. You bring the news that God has already taken the first step. You simply deliver the message, trembling hands and all.",
            "tags": [
              "theme:mission",
              "posture:seeking",
              "tone:resolute"
            ]
          },
          {
            "id": "perdon",
            "label": "Someone I have to apologize to",
            "insight": "That is the most expensive and most credible ministry. The evidence that you reconciled with God is that you seek reconciliation with people.",
            "tags": [
              "theme:humility",
              "posture:humble",
              "tone:raw"
            ]
          },
          {
            "id": "herido",
            "label": "Someone who is suffering right now",
            "insight": "Your crack makes you useful here. No one comforts better than someone who was comforted through the same kind of dark night (2 Cor. 1:4).",
            "tags": [
              "theme:service",
              "theme:grace",
              "tone:tender"
            ]
          },
          {
            "id": "yo",
            "label": "Myself, I still don't believe myself forgiven",
            "insight": "Before being an ambassador you have to be reconciled. \"If anyone is in Christ, he is a new creature\" (2 Cor. 5:17). That has already been said about you, even if you don't feel it today.",
            "tags": [
              "react:doubt",
              "theme:cross",
              "posture:clinging"
            ]
          }
        ]
      }
    },
    {
      "id": "santidad",
      "day": "Wednesday · A call to holiness",
      "tag": "Piece 6 What I set aside",
      "title": "First the promise, then the step",
      "story": "Here it is easy to reverse the order. Paul says, \"Come out,\" \"be separate,\" and \"touch no unclean thing\" (2 Cor. 6:17), and we first hear a list of demands. But notice what comes before: \"I will live with them... I will be their God... I will receive you... I will be a Father to you\" (2 Cor. 6:16-18). Promise comes first; the imperatives follow \"therefore.\" Holiness is not the price of his presence. It makes room for a presence already promised to you.",
      "cue": "Keep this order clear, {name}, because your rest depends on it.",
      "module": {
        "type": "skillThenCommit",
        "saveLabel": "Save to my vessel",
        "seedSub": "What you set aside",
        "skill": {
          "prompt": "Work of the Spirit or human effort? Classify each sentence.",
          "hint": "Listen if the phrase is born from a promise or a requirement",
          "badge": "You are learning to distinguish grace from strain",
          "cats": [
            "Work of the Spirit",
            "Human effort"
          ],
          "rounds": [
            {
              "t": "\"I will receive you, and I will be your Father, and you will be my sons and daughters.\"",
              "a": 0,
              "fb": "Work of the Spirit. It is pure promise (2 Cor. 6:17-18). God commits before asking you for anything."
            },
            {
              "t": "\"If I make enough effort, I may deserve God to accept me.\"",
              "a": 1,
              "fb": "Human effort. That is the old covenant lived as legalism. You were already accepted in Christ, not because of your performance."
            },
            {
              "t": "\"Let's cleanse ourselves, because we have these promises\" (2 Cor. 7:1).",
              "a": 0,
              "fb": "Work of the Spirit. Note the \"because\": the promise is the engine, and cleansing is the result."
            },
            {
              "t": "\"My holiness is that no one notices my faults.\"",
              "a": 1,
              "fb": "Human effort. That is appearance, not holiness. A vessel painted on the outside can still be empty inside."
            },
            {
              "t": "\"I depart from what harms me because he promised to dwell in me.\"",
              "a": 0,
              "fb": "Work of the Spirit. You set something aside out of love for the One who lives within you, not out of fear of those watching you."
            },
            {
              "t": "\"God will love me more on the day I finally get it right.\"",
              "a": 1,
              "fb": "Human effort. His love does not rise or fall with your week. He already loved you at your worst and did not change his mind."
            }
          ],
          "summary": "You do not produce holiness; the Spirit produces it in a heart that makes room for him. Your part is real, but it comes second: you reject what contaminates you because you are already God's child, not to become one."
        },
        "commit": {
          "prompt": "What are you going to set aside this week to make room for it?",
          "hint": "One specific thing, not an impossible list",
          "placeholder": "This week I'm going to set aside...",
          "extraKey": "apartarTexto",
          "options": [
            "A consumption that leaves me dirty inside",
            "A relationship that is turning me off",
            "The resentment that I keep feeding in silence",
            "The rush that won't let me hear it",
            "A small lie that has already become customary"
          ]
        }
      }
    },
    {
      "id": "consuelo",
      "day": "Thursday · Comfort and joy",
      "tag": "Piece 7 · The comfort I receive",
      "title": "The God of all comfort",
      "story": "The letter ends where it began: with comfort. Paul had written through tears and waited in anguish. When Titus arrived with good news, Paul burst out: \"I am greatly encouraged; in all our troubles my joy knows no bounds\" (2 Cor. 7:4). Notice the word \"in.\" He does not say despite, but in. He knows where the comfort came from: \"the God of all comfort, who comforts us in all our troubles\" (2 Cor. 1:3-4). Even sorrow had a place, because God can use one kind of pain: \"Godly sorrow brings repentance that leads to salvation\" (2 Cor. 7:10).",
      "cue": "Receive something before you go, {name}. This is not only a time to give.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "What do you need today from the God of all comfort?",
        "hint": "Ask for what you really lack, not what sounds spiritual",
        "saveLabel": "Save to my vessel",
        "seedSub": "Your comfort",
        "closing": "The comfort you receive never remains still: God comforts us \"so that we can comfort those in any trouble with the comfort we ourselves receive\" (2 Cor. 1:4). What God gives you today may become someone else's bread tomorrow.",
        "options": [
          {
            "id": "descanso",
            "label": "I rest, I'm exhausted",
            "insight": "He will not squeeze more out of you. The same One who called you to work also calls you to rest, and he does not love you less for being tired.",
            "tags": [
              "theme:grace",
              "posture:surrendering",
              "tone:tender"
            ]
          },
          {
            "id": "perdon",
            "label": "Forgiveness, I carry an old guilt",
            "insight": "\"Godly sorrow brings repentance that leads to salvation and leaves no regret\" (2 Cor. 7:10). The pain that leads you to him heals; the pain that drives you away only pulls you under.",
            "tags": [
              "theme:sin",
              "posture:humble",
              "tone:raw"
            ]
          },
          {
            "id": "compania",
            "label": "Company, I feel very lonely",
            "insight": "\"Persecuted, but not abandoned\" (2 Cor. 4:9). Abandoned is the one thing you are not, even if it feels that way today.",
            "tags": [
              "react:withdraw",
              "theme:hope",
              "posture:clinging"
            ]
          },
          {
            "id": "certeza",
            "label": "Certainty, I doubt everything",
            "insight": "Paul was also perplexed, yet he kept going (2 Cor. 4:8). Faith is not the absence of questions; it is continuing to walk while carrying them.",
            "tags": [
              "react:doubt",
              "theme:faith",
              "posture:seeking"
            ]
          },
          {
            "id": "gozo",
            "label": "Joy, I haven't laughed in a long time",
            "insight": "Paul abounded in joy in the midst of tribulation, not after it was over. Joy does not wait for everything to clear.",
            "tags": [
              "theme:hope",
              "theme:prayer",
              "tone:tender"
            ]
          },
          {
            "id": "valor",
            "label": "Courage, I have to do something hard",
            "insight": "Paul wrote the hard letter he didn't want to write, and that letter produced life. Sometimes love demands the conversation you are avoiding.",
            "tags": [
              "theme:truth",
              "posture:seeking",
              "tone:resolute"
            ]
          }
        ]
      }
    },
    {
      "id": "paso",
      "day": "Friday · To study and meditate",
      "tag": "Piece 8 · My step of the week",
      "title": "Go out with the vessel in your hand",
      "story": "\"As a church we have received great light. The Lord has entrusted this light to us for the benefit and blessing of the world. The ministry of reconciliation has been given to us\" (Ellen G. White, Letter 32, 1903). Do not wait for a day when the vessel has no cracks. That day will not come. The light you carry is not extinguished by your flaws; it becomes visible through them. Go and tell someone what God is doing with your clay.",
      "cue": "One last step, {name}. Make it small and real.",
      "module": {
        "type": "commitDuo",
        "saveLabel": "Close my vessel",
        "seedSub": "Your step",
        "stepPrompt": "My concrete step this week",
        "stepHint": "Touch an idea or write yours",
        "stepOptions": [
          "Tell someone my crack without decorating it",
          "Find the person I need to reconcile with",
          "Read 2 Corinthians 4 full, slowly, every morning",
          "Serve even though today I don't feel capable",
          "Stop hiding my tiredness before God"
        ],
        "stepPlaceholder": "My concrete step...",
        "stepExtraKey": "pasoTexto",
        "personPrompt": "Someone who needs to hear that God uses broken vessels",
        "personHint": "Who will you bring this comfort to?",
        "personPlaceholder": "A name...",
        "personExtraKey": "compartir"
      }
    }
  ],
  "encourage": [
    "\"We have this treasure in jars of clay to show that this surpassing power is from God and not from us.\" (2 Cor. 4:7)",
    "\"We are hard pressed on every side, but not crushed; perplexed, but not in despair.\" (2 Cor. 4:8)",
    "\"Though outwardly we are wasting away, inwardly we are being renewed day by day.\" (2 Cor. 4:16)",
    "\"Our light and momentary troubles are achieving for us an eternal glory that far outweighs them all.\" (2 Cor. 4:17)",
    "\"If anyone is in Christ, the new creation has come; the old has gone, the new is here!\" (2 Cor. 5:17)",
    "\"Blessed be the God of all comfort, who comforts us in all our troubles.\" (2 Cor. 1:3-4)"
  ],
  "discussion": [
    "Paul calls us \"jars of clay\" that contain the treasure of the gospel (2 Cor. 4:7). How can our fragility strengthen, rather than weaken, its proclamation?",
    "What does it mean in practice to be \"a new creation\" (2 Cor. 5:17), and in what specific part of your daily life is it noticeable?",
    "Paul calls his suffering \"mild and momentary\" (2 Cor. 4:17). How does that look hold when what you are living does not feel light or momentary?",
    "Paul distinguishes the sadness that is according to God from the sadness of the world (2 Cor. 7:10). How is the difference recognized in one's experience?"
  ],
  "facilitator": [
    {
      "stationId": "barro",
      "apertura": "What image comes to your mind when Paul describes himself as a clay vessel?",
      "seguimiento": "What part of your fragility is more difficult for you to accept before God?",
      "ilustracion": "Clay was the cheapest material in Corinth: people used it and discarded it when it broke. God chose that container on purpose.",
      "transicion": "If the vessel is clay, the next question is what then proves an authentic ministry.",
      "actividad": "Invite each person to name in one word how they arrived today, without explaining or justifying.",
      "cierre": "Lord, receive us as we arrived, with the clay in sight."
    },
    {
      "stationId": "carta",
      "apertura": "Paul did not carry letters of recommendation (2 Cor. 3:1). What was he carrying in his place?",
      "seguimiento": "Who is your letter written on today, even if you have never thought so?",
      "ilustracion": "In the Greco-Roman world they did not receive you without a sealed letter. Paul pointed to an entire church and said: My letter is you.",
      "transicion": "That endorsement was written in the midst of suffering. Let's go to the passage where Paul explains it.",
      "actividad": "Read 2 Corinthians 3:1-6 and identify where Paul says his competence comes from.",
      "cierre": "Write through us, Lord, what we could never sign on our own."
    },
    {
      "stationId": "grieta",
      "apertura": "Why do you think God puts his treasure in a cracking container?",
      "seguimiento": "What crack have you tried to hide because it embarrassed you?",
      "ilustracion": "A sealed vessel keeps light inside. A cracked one lets it out. The crack is not a defect in the plan.",
      "transicion": "If the crack hurts, you need to put that pain on the right balance.",
      "actividad": "Read 2 Corinthians 4:8-10 aloud and underline each \"but.\"",
      "cierre": "Thank you, Lord, because you use the very thing we thought was useless."
    },
    {
      "stationId": "peso",
      "apertura": "How can Paul call a life of prisons and beatings \"light and momentary\"?",
      "seguimiento": "What changes in your week if you really think this has a deadline?",
      "ilustracion": "Picture the two pans of a scale: in one, everything that weighs on you today; in the other, an eternal weight of glory that does not fit in this life.",
      "transicion": "Anyone comforted in this way receives something to share: the ministry of reconciliation.",
      "actividad": "Read 2 Corinthians 4:16-18 and discuss what it means to look at what is not seen.",
      "cierre": "Support us, Lord, with the eternal when the visible crushes us."
    },
    {
      "stationId": "embajada",
      "apertura": "What does an ambassador do, and how does that resemble the Christian life (2 Cor. 5:20)?",
      "seguimiento": "Who is God sending you to this week, although you would rather not go?",
      "ilustracion": "An ambassador does not speak on their own behalf or negotiate their own terms. They carry a message they did not invent.",
      "transicion": "A person reconciled with God then seeks holiness. Let's see the order in which that happens.",
      "actividad": "Read 2 Corinthians 5:16-21 and tell how many times the word reconciliation appears.",
      "cierre": "Send us, Lord, with empty hands and your message in your mouth."
    },
    {
      "stationId": "santidad",
      "apertura": "In 2 Corinthians 6:16-18, what comes first: God's promises or his commands?",
      "seguimiento": "What are you trying to achieve by self-effort that only the Spirit can do in you?",
      "ilustracion": "The \"therefore\" in 2 Corinthians 6:17 is a hinge: everything God promises supports everything he asks of us.",
      "transicion": "Once we understand that order, we can see what Paul felt near the end of the letter: comfort and joy.",
      "actividad": "List the four promises of 2 Corinthians 6:16 and the three imperatives of 6:17 together.",
      "cierre": "Sanctify us, Lord, because we cannot."
    },
    {
      "stationId": "consuelo",
      "apertura": "Paul says that he abounds in joy \"in\" his tribulations, not later. How is that possible?",
      "seguimiento": "Have you experienced a sorrow that drew you closer to God instead of driving you away? How did you recognize it?",
      "ilustracion": "The word comfort appears again and again in 2 Corinthians 7. The letter begins and ends in the same place.",
      "transicion": "Having received that comfort, we will close with one specific step for the next few days.",
      "actividad": "Read 2 Corinthians 7:9-11 and contrast godly sorrow with worldly sorrow.",
      "cierre": "Comfort us, Father, so that we can comfort others."
    },
    {
      "stationId": "paso",
      "apertura": "What does it mean that God has entrusted the ministry of reconciliation to us?",
      "seguimiento": "Who do you know who needs to hear this week that God uses broken vessels?",
      "ilustracion": "No one waits for a vessel to be perfect before pouring water. You serve with the vessel you have.",
      "transicion": "We gather everything in a single concrete step and in a name.",
      "actividad": "Share a step for this week and the person you are going to tell it to.",
      "cierre": "Use us as we are, Lord, and let the treasure be seen and not the clay."
    }
  ],
  "patternTemplate": "{name}, you arrived acknowledging that your clay felt like this: {slot:barro|lower}. Instead of covering the crack, you named it. You discovered that this exact place is where the light escapes. You no longer carry the vessel to display it, but so others can see whose treasure it holds.",
  "outOracion": "Lord, I come to you with my clay in plain sight: today I feel {slot:barro|lower}. I give you the crack I have hidden, the one called {slot:grieta|or:my fragility}. Teach me to believe that this is where your light shines through. In your presence I seal this hope: {slot:peso|lower}. Send me as your ambassador to {slot:embajada|lower}, and help me set aside {slot:santidad|lower} to make room for you. Give me the comfort I need today: {slot:consuelo|lower}. May the surpassing power be yours and not mine, because \"{verse}\" ({verseRef}). In the name of Jesus, amen.",
  "outAliento": "{name}, you are not too weak for God. You are exactly the vessel he chose. The very crack that embarrasses you is where others can see the treasure. You decided to seal this hope: {slot:peso|lower}. Go out as you are, cracked and full, because the light does not shine despite your fracture; it shines through it.",
  "outAccion24": "In the next 24 hours I'm going to {slot:paso|lower}, and I'm going to set aside {slot:santidad|lower} to make room for God.",
  "outPregunta": "This week I understood that God puts his treasure in clay vessels, and I stopped hiding my crack. I sealed this hope: {slot:peso|lower}. What is the fragility that you think disqualifies you, and what would happen if God used it?",
  "outTarjeta": "My vessel this week: I arrived {slot:barro|lower}, I named my crack and sealed this hope: {slot:peso|lower}. The power is from God and not mine. Verse: \"{verse}\" ({verseRef}).",
  "arc": "REVEAL"
}
);
