import { makeLesson } from "../../engine/makeLesson.js";

/* Lesson 12 · Q3 2026 · 1 and 2 Corinthians
   Authored from the official quarterly, then adapted for this engine.
   Generated by scripts/build-lessons.mjs. Edit the draft, not this file. */
export default makeLesson(
{
  "number": 12,
  "slug": "derribar-fortalezas",
  "title": "Tearing Down Strongholds",
  "forDate": "2026-09-19",
  "subtitle": "What if the stronghold that must fall is inside you?",
  "kitName": "My Stronghold",
  "artifactNoun": "stronghold",
  "motif": "muro",
  "stages": [
    "muro",
    "grieta",
    "brecha",
    "cimiento",
    "refugio"
  ],
  "stageLabels": [
    "Closed wall · I defend myself",
    "First crack · I face myself",
    "A breach opens · I name the lie",
    "The foundation remains · I show my weakness",
    "Stronghold in God · his grace is enough"
  ],
  "verseRef": "2 Cor. 10:4",
  "verseText": "For the weapons of our warfare are not worldly, but mighty through God for tearing down strongholds.",
  "promise": "In a few minutes you will raise your Stronghold, {name}: you will name the argument entrenched in your mind, learn to distinguish a true message from an impressive one, stop hiding the weakness you cover, and hear the only answer Paul received. Piece by piece, what was a wall will become a refuge.",
  "ui": {
    "start": "Begin raising my stronghold",
    "emptyKit": "Your stronghold",
    "building": "Each piece tears down a wall",
    "buildingHint": "Tap the glowing piece. Watch what once defended you fall and what truly sustains you rise.",
    "lastPiece": "One piece remains",
    "patternLabel": "Your pattern in the clay",
    "doneTitle": "Your stronghold is standing",
    "doneSub": "You did not raise it with arguments, but with grace. Open it, save it, and share it.",
    "open": "Open my stronghold",
    "back": "Back to my stronghold",
    "kitName": "My Stronghold"
  },
  "slots": [
    {
      "id": "muro",
      "n": 1,
      "label": "The stronghold that falls",
      "teaser": "The argument that grew strong inside me...",
      "icon": "cloud"
    },
    {
      "id": "armas",
      "n": 2,
      "label": "My true weapons",
      "teaser": "Firm with error, tender with the person...",
      "icon": "hand"
    },
    {
      "id": "gloria",
      "n": 3,
      "label": "My reason to boast",
      "teaser": "I stop comparing myself and boast in him...",
      "icon": "sun"
    },
    {
      "id": "discernir",
      "n": 4,
      "label": "My filter",
      "teaser": "The measure I use for what I hear...",
      "icon": "eye"
    },
    {
      "id": "cicatriz",
      "n": 5,
      "label": "My scar",
      "teaser": "What following him has cost me...",
      "icon": "path"
    },
    {
      "id": "espina",
      "n": 6,
      "label": "What I stop hiding",
      "teaser": "My weakness, finally brought into the light...",
      "icon": "heart"
    },
    {
      "id": "gracia",
      "n": 7,
      "label": "The grace that is enough",
      "teaser": "His power made perfect in my weakness...",
      "icon": "anchor"
    },
    {
      "id": "paso",
      "n": 8,
      "label": "My step this week",
      "teaser": "One concrete step and someone I will accompany...",
      "icon": "flame"
    }
  ],
  "stations": [
    {
      "id": "muro",
      "day": "Saturday · The war that is not seen",
      "tag": "Slot 1 · The stronghold that falls",
      "title": "The weapons are not what you think",
      "story": "Polished preachers appeared in Corinth: fine voices, long credentials, and a presence that filled the room. Beside them Paul seemed unimpressive. He did not answer with more polish, but with a different kind of weapon: \"The weapons we fight with are not the weapons of the world. On the contrary, they have divine power to demolish strongholds\" (2 Cor. 10:4). The first stronghold to fall is rarely someone else's. It is an argument entrenched in your own mind, issuing orders from there.",
      "cue": "Before looking out, {name}, look at the wall inside you.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "What argument has become strong within you?",
        "hint": "Choose the one that rules the most today, not the one that sounds the best",
        "saveLabel": "Save to my stronghold",
        "seedSub": "Your stronghold",
        "closing": "None of these walls falls by force of will. They fall when the word comes in, \"knocking down arguments and all arrogance that rises up against the knowledge of God\" (2 Cor. 10:5).",
        "options": [
          {
            "id": "impresionar",
            "label": "If I don't impress, I'm not worth it",
            "insight": "That is exactly the stronghold Corinth embraced: polish mistaken for truth. God called you when no one applauded, and he does not check your stage presence before using you.",
            "tags": [
              "react:pride",
              "theme:self",
              "tone:raw"
            ]
          },
          {
            "id": "solo",
            "label": "No one would understand what I have",
            "insight": "No one may fully understand it. But the wall that protects you also leaves you without help, and God almost always sends comfort with hands and with names.",
            "tags": [
              "react:withdraw",
              "posture:avoidant",
              "tone:tender"
            ]
          },
          {
            "id": "sabelotodo",
            "label": "I already know all this",
            "insight": "\"Long-cherished opinions are not to be regarded as infallible\" (The Other Power, p. 31). Knowing doctrine and being in the faith are not always the same thing.",
            "tags": [
              "react:pride",
              "posture:proud",
              "theme:word"
            ]
          },
          {
            "id": "merecer",
            "label": "God will love me more if I surrender more",
            "insight": "That wall is called merit and falls with a single phrase: \"My grace is enough\" (2 Cor. 12:9). Your performance cannot buy what he already gave you.",
            "tags": [
              "theme:grace",
              "posture:clinging",
              "react:control"
            ]
          },
          {
            "id": "sentir",
            "label": "What I feel is what is true",
            "insight": "Feeling is a good witness and lousy judge. Bring your ideas to the word, instead of reading the word in the light of your ideas.",
            "tags": [
              "react:doubt",
              "theme:truth",
              "posture:seeking"
            ]
          },
          {
            "id": "dudar",
            "label": "Yes I doubt, I don't think anymore",
            "insight": "Doubt is not apostasy. Paul was burdened beyond his strength and remained an apostle. Doubt brought honestly to God has already become prayer.",
            "tags": [
              "react:fear",
              "theme:faith",
              "tone:tender"
            ]
          }
        ]
      }
    },
    {
      "id": "armas",
      "day": "Sunday Spiritual Warfare",
      "tag": "Slot 2 · My true weapons",
      "title": "Meek and brave at the same time",
      "story": "They accused him of being fierce by letter and timid in person (2 Cor. 10:10). Paul did not defend himself with pride. He appealed \"by the meekness and gentleness of Christ\" (2 Cor. 10:1), while warning that he would not shrink back. Jesus lived this way: \"gentle and humble in heart\" (Matt. 11:29), yet willing to overturn the tables in the temple. Paul's war was not against people, but against arguments and arrogance, \"taking every thought captive to obey Christ\" (2 Cor. 10:5). The authority he received was \"for building you up, not for tearing you down\" (2 Cor. 10:8).",
      "cue": "{name}, here you decide what to fight and what not to fight.",
      "module": {
        "type": "perspectiveFlip",
        "saveLabel": "Save to my stronghold",
        "seedSub": "Your weapons",
        "prompt": "Tap each card and see your weapons as God sees them",
        "hint": "What seems weak, and what is actually strong",
        "pairs": [
          {
            "see": "Your meekness seems like a lack of character.",
            "sees": "\"I am gentle and humble in heart\" (Matt. 11:29). That gentleness moved more than all the force of Rome."
          },
          {
            "see": "The person who speaks louder seems to be right.",
            "sees": "\"The weapons we fight with are not the weapons of the world\" (2 Cor. 10:4). Volume was never authority."
          },
          {
            "see": "You think the fight is against people.",
            "sees": "The battle is against arguments and arrogance (2 Cor. 10:5). Win the person over; tear the error down."
          },
          {
            "see": "You always stay silent so you will not upset anyone.",
            "sees": "His authority is \"for building and not for destruction\" (2 Cor. 10:8). Telling the truth tenderly can also build someone up."
          }
        ],
        "chooseLabel": "This is the truth I needed",
        "teach": "Firmness and tenderness are not opposites; they are the two hands of Christ himself. Without firmness, error is allowed to live in the church. Without tenderness, you win the argument and lose your brother or sister.",
        "commit": {
          "prompt": "Write how you will fight this week: firm with error, tender with the person",
          "hint": "Name a concrete conversation, not a theory",
          "placeholder": "This week I'm going to...",
          "extraKey": "armasPropias",
          "shareable": true
        }
      }
    },
    {
      "id": "gloria",
      "day": "Monday · Boast in the Lord",
      "tag": "Slot 3 · My reason to boast",
      "title": "Stop measuring yourself against others",
      "story": "The false teachers measured themselves by one another and commended themselves. Paul bluntly calls this \"not wise\" (2 Cor. 10:12). He chooses different ground: \"Let the one who boasts boast in the Lord\" (2 Cor. 10:17), quoting Jeremiah: \"Let the one who boasts boast about this: that they have the understanding to know me\" (Jer. 9:24). This is the exit from rivalry. You do not escape comparison by winning, but by changing the center from your achievements to the mercy, justice, and righteousness of the God who knows you.",
      "cue": "Be honest here, {name}. No one else is going to read this.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "If you were completely honest, what do you find yourself boasting about, even inwardly?",
        "hint": "We all boast about something. The question is what",
        "saveLabel": "Save to my stronghold",
        "seedSub": "Your boast",
        "closing": "None of that is bad in itself. The danger is building your identity on it. \"Let the one who boasts boast about this: that they have the understanding to know me\" (Jer. 9:24). The only ground you cannot lose is God himself.",
        "options": [
          {
            "id": "conocimiento",
            "label": "How much I know about the Bible",
            "insight": "Knowledge without humility becomes a wall. Corinth's false teachers had the same credentials as Paul; what they lacked was his heart.",
            "tags": [
              "react:pride",
              "theme:word",
              "posture:proud"
            ]
          },
          {
            "id": "servicio",
            "label": "How much I serve in the church",
            "insight": "Thank you for serving. But be careful: if your peace depends on being noticed, you are no longer serving freely; you are collecting payment.",
            "tags": [
              "theme:service",
              "react:control",
              "posture:clinging"
            ]
          },
          {
            "id": "sufrimiento",
            "label": "How much I have had to suffer",
            "insight": "Paul also made his list, while making clear that he spoke as a fool (2 Cor. 11:16-21). Your pain is real and God sees it; it does not have to become your credential.",
            "tags": [
              "theme:self",
              "tone:raw",
              "posture:seeking"
            ]
          },
          {
            "id": "disciplina",
            "label": "My discipline and perseverance",
            "insight": "Your perseverance is a gift that God sustains, not a merit that you accumulate. The day you fail, grace will remain exactly as firm.",
            "tags": [
              "react:control",
              "theme:faith",
              "tone:resolute"
            ]
          },
          {
            "id": "autentico",
            "label": "Not being like people who only keep up appearances",
            "insight": "Beware: boasting one's humility is the most elegant trap that exists. The comparison changed direction, but it is still a comparison.",
            "tags": [
              "react:pride",
              "theme:humility",
              "posture:proud"
            ]
          },
          {
            "id": "nada",
            "label": "Nothing, and that makes me feel inferior",
            "insight": "Then you are exactly where Paul wanted to arrive. The person with nothing left to boast about has all the room in the world to boast in the Lord.",
            "tags": [
              "react:fear",
              "theme:grace",
              "tone:tender"
            ]
          }
        ]
      }
    },
    {
      "id": "discernir",
      "day": "Tuesday · False teachers are identified",
      "tag": "Slot 4 My Filter",
      "title": "True is not the same as impressive",
      "story": "Paul saw himself as a father presenting the bride: \"I promised you to one husband, to Christ, so that I might present you as a pure virgin to him\" (2 Cor. 11:2). This is why it hurt when others preached \"a Jesus other than the Jesus we preached\" and \"a different gospel\" (2 Cor. 11:4). His warning is severe and necessary: there are \"false apostles, deceitful workers, masquerading as apostles of Christ,\" just as \"Satan himself masquerades as an angel of light\" (2 Cor. 11:13-14). The disguise always looks bright. This is why beauty alone is not a sufficient filter.",
      "cue": "Train your ear here, {name}. It will serve you all your life.",
      "module": {
        "type": "skillThenCommit",
        "saveLabel": "Save to my stronghold",
        "seedSub": "Your filter",
        "skill": {
          "prompt": "Does this message take you to Christ, or does it take you to the messenger?",
          "hint": "Not everything that impresses is true, and not everything true impresses",
          "badge": "You're learning to test what you hear",
          "cats": [
            "Points to Christ",
            "Points to the messenger"
          ],
          "rounds": [
            {
              "t": "\"Listen well: God revealed this only to me, no one else has it.\"",
              "a": 1,
              "fb": "Points to the messenger. Claims of exclusive revelation are a mark of error. Truth is tested by the Word, which is open to all."
            },
            {
              "t": "\"Check it in your Bible, even if you discover that I am wrong.\"",
              "a": 0,
              "fb": "Points to Christ. Whoever sends you back to the Word is not binding you to their own personality."
            },
            {
              "t": "\"If you follow me, your life will finally take off.\"",
              "a": 1,
              "fb": "Points to the messenger. The gospel does not promise upward mobility; it promises Christ, and sometimes scars (2 Cor. 11:23-28)."
            },
            {
              "t": "\"Christ died for you; nothing you do can add merit to that cross.\"",
              "a": 0,
              "fb": "Points to Christ. The center is what he did, not what you produce."
            },
            {
              "t": "\"Those who doubt me are in rebellion against God.\"",
              "a": 1,
              "fb": "Points to the messenger. Equating a person with God is the exact trap. \"Satan disguises himself as an angel of light\" (2 Cor. 11:14)."
            },
            {
              "t": "\"My greatest desire is to present you pure to Christ, not to hold you with me.\"",
              "a": 0,
              "fb": "Points to Christ. That was Paul's desire: to present the bride to her husband (2 Cor. 11:2)."
            }
          ],
          "summary": "A true message leaves you looking at Jesus and with the Bible open. An impressive message leaves you looking at whoever speaks. The proof is not the charisma, nor the eloquence, nor the credentials: it is where it leaves you standing."
        },
        "commit": {
          "prompt": "What will you use to measure what you hear this week?",
          "hint": "Choose a filter that you can really use, not a nice one",
          "placeholder": "I'm going to measure what I hear from...",
          "extraKey": "filtro",
          "options": [
            "Open the Bible before accepting it",
            "Ask whom it leaves at the center",
            "Check for humility or vanity",
            "Discuss it with someone mature in faith",
            "See whether it draws me closer to the church or isolates me"
          ]
        }
      }
    },
    {
      "id": "cicatriz",
      "day": "Wednesday · Suffering because of the Gospel",
      "tag": "Slot 5 · My scar",
      "title": "His credentials were scars",
      "story": "When it was finally his turn to present a résumé, Paul did not list titles. He spoke of lashes, prison, shipwreck, hunger, cold, dangers of every kind, and one burden hardly anyone saw: \"the pressure of my concern for all the churches\" (2 Cor. 11:28). The false teachers had the same ancestry he did (2 Cor. 11:22). What they lacked were the scars. Only a true servant of Christ would willingly pay that price for a gospel that did not belong to him.",
      "cue": "Your list is shorter than Paul's, {name}, but God cares about every item.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "What has it cost you to follow Christ?",
        "hint": "It doesn't have to be big to make it real",
        "saveLabel": "Save to my stronghold",
        "seedSub": "Your scar",
        "closing": "Keep that scar without displaying it. It is neither a credential nor a bill; it is quiet evidence that what you believe matters more than what it costs you.",
        "options": [
          {
            "id": "amistad",
            "label": "A friendship that cooled down",
            "insight": "It hurts to lose people along the way. Jesus experienced that before you and promised a new family to anyone who leaves something for his sake (Mark 10:29-30).",
            "tags": [
              "theme:relationship",
              "posture:surrendering",
              "tone:tender"
            ]
          },
          {
            "id": "burla",
            "label": "Teasing where I study or work",
            "insight": "Mockery can wear you down more than open persecution because it comes in small doses every day. Blessed are you when people insult you because of him (Matt. 5:11).",
            "tags": [
              "react:fear",
              "theme:mission",
              "tone:raw"
            ]
          },
          {
            "id": "dinero",
            "label": "Money or an opportunity that I let go",
            "insight": "Paul gave up his right to financial support so he would not be a burden (2 Cor. 11:7-12). What you release out of faithfulness is never lost; it changes hands.",
            "tags": [
              "theme:generosity",
              "posture:surrendering",
              "tone:resolute"
            ]
          },
          {
            "id": "casa",
            "label": "That in my own house they do not understand me",
            "insight": "This is one of the heaviest costs because you cannot simply go elsewhere. Keep loving without preaching at them. Your daily life may become the argument they will hear.",
            "tags": [
              "theme:relationship",
              "react:withdraw",
              "tone:raw"
            ]
          },
          {
            "id": "cansancio",
            "label": "A tiredness that no one sees",
            "insight": "Paul called that \"the pressure of my concern for all the churches\" (2 Cor. 11:28). Heaven counts the invisible strain even when no one applauds it.",
            "tags": [
              "react:apathy",
              "theme:hope",
              "tone:tender"
            ]
          },
          {
            "id": "esperar",
            "label": "Carrying for years with people who don't change",
            "insight": "Praying without seeing an answer is a quiet way of suffering for the gospel. Keep praying: God works on a timetable that does not consult you.",
            "tags": [
              "theme:prayer",
              "posture:clinging",
              "react:doubt"
            ]
          }
        ]
      }
    },
    {
      "id": "espina",
      "day": "Wednesday · The thorn that did not leave",
      "tag": "Slot 6 · What I stopped hiding",
      "title": "My grace is enough",
      "story": "To keep him from becoming conceited, Paul was given \"a thorn in my flesh\" (2 Cor. 12:7). Three times he pleaded with the Lord to remove it. The Lord did not remove it. He gave Paul something better: \"My grace is sufficient for you, for my power is made perfect in weakness\" (2 Cor. 12:9). That is where competition with the \"super-apostles\" ended. Paul stopped hiding his fragile side and began to boast in it, because he discovered the exact place where God becomes visible.",
      "cue": "Climb with open hands, {name}. There is no ridicule on the other side.",
      "module": {
        "type": "stairs",
        "saveLabel": "Save to my stronghold",
        "seedSub": "Your thorn",
        "climbPrompt": "Climb up carrying the thorn in your hand, without covering it",
        "climbHint": "Three times Paul asked for it to be removed. The answer was different, and it was better.",
        "leavePrompt": "What weakness are you going to stop hiding?",
        "leaveHint": "Leave it at the door. The costume is not needed here.",
        "leaveOptions": [
          "My anxiety",
          "A pain in the body that does not go away",
          "I don't know how to explain my faith",
          "A temptation that returns",
          "That inside I'm exhausted"
        ],
        "allowCustom": {
          "placeholder": "The weakness I hide is...",
          "extraKey": "debilidadPropia"
        },
        "promisePrompt": "Listen to what he answers",
        "promiseOptions": [
          {
            "t": "\"My grace is enough.\"",
            "w": "He does not promise to remove it. He promises to hold you within his grace every day."
          },
          {
            "t": "\"My power is perfected in weakness.\"",
            "w": "Right where you feel less useful, he becomes more visible to others."
          },
          {
            "t": "\"When I'm weak, then I'm strong.\"",
            "w": "The strength you were seeking begins the day you stop pretending you do not need it."
          },
          {
            "t": "\"I will boast all the more gladly about my weaknesses.\"",
            "w": "What you hid can become the most credible testimony you have."
          }
        ],
        "verse": {
          "text": "My grace is enough, because my power is perfected in weakness.",
          "ref": "2 Cor. 12:9"
        },
        "promiseExtraKey": "respuestaGracia"
      }
    },
    {
      "id": "gracia",
      "day": "Thursday Examine yourselves",
      "tag": "Slot 7 · The grace that is enough for me",
      "title": "The test that does matter",
      "story": "Paul announced his third visit to Corinth and explained why he was coming: not to win an argument, but to restore. \"Our prayer is that you may be fully restored\" (2 Cor. 13:9). In the middle of his conflict with the false teachers, he turned the examination toward them and toward us: \"Examine yourselves to see whether you are in the faith\" (2 Cor. 13:5). The final question was never who preaches best. It is whether Christ lives in you. Gather what fell and what remained, and see what is still standing.",
      "cue": "This is what holds everything else, {name}. Receive it.",
      "module": {
        "type": "anchorChain",
        "saveLabel": "Receive his grace and keep",
        "seedSub": "The grace that is enough for you",
        "chain": [
          {
            "word": "Ideas are examined, not people",
            "line": "We take down arguments and arrogance (2 Cor. 10:5), and we treat the brother with the tenderness of Christ."
          },
          {
            "word": "The exam starts with me",
            "line": "\"Examine yourselves to see if you are in faith\" (2 Cor. 13:5). First my heart, then the mistake of others."
          },
          {
            "word": "The correction seeks to restore",
            "line": "\"We pray to God for you to be fully restored\" (2 Cor. 13:9). It was never tried to punish."
          },
          {
            "word": "His grace is enough for me",
            "line": "I no longer have to impress anyone. His power is perfected just where I am weak (2 Cor. 12:9)."
          }
        ],
        "climax": "Your stronghold is no longer your own resistance. It is Christ dwelling in you, and his grace is enough every day.",
        "prompt": "What truth are you going to sustain when the voice that impresses you returns?",
        "hint": "Choose the one you need to repeat out loud this week",
        "options": [
          "That Christ lives in me, and that is enough for me",
          "That grace does not depend on my performance",
          "That the truth is tested in the word, not in the brightness",
          "That my weakness is the place where he shows himself"
        ],
        "allowCustom": {
          "placeholder": "I'm going to argue that...",
          "extraKey": "verdadSostenida"
        }
      }
    },
    {
      "id": "paso",
      "day": "Friday · To study and meditate",
      "tag": "Slot 8 · My step of the week",
      "title": "Firm, and without fighting anyone",
      "story": "\"If they would only bring their doctrines to the Word of God, instead of reading the Bible in the light of their doctrines, they would not walk in darkness\" (Ellen G. White, The Other Power, p. 31). This is the week's work, and it is not done in the abstract. It is done with an open Bible, a humble heart, and someone beside you. A stronghold in God does not rise through arguments on social media. It rises in concrete, small acts. One piece remains: what will you do, and with whom?",
      "cue": "Close with something you can do tomorrow, {name}, not one day.",
      "module": {
        "type": "commitDuo",
        "saveLabel": "Close my stronghold",
        "seedSub": "Your step",
        "stepPrompt": "My concrete step this week",
        "stepHint": "Touch an idea or write yours",
        "stepOptions": [
          "Check in the Bible everything you hear",
          "Confess my weakness to someone you trust",
          "Leave an argument that does not build",
          "Speak firmly and tenderly with that person",
          "Pray every day for whoever teaches in my church"
        ],
        "stepPlaceholder": "My concrete step...",
        "stepExtraKey": "pasoTexto",
        "personPrompt": "Someone I'm going to accompany",
        "personHint": "Who is listening to voices that take him away from Christ?",
        "personPlaceholder": "A name...",
        "personExtraKey": "compartir"
      }
    }
  ],
  "encourage": [
    "\"Because the weapons of our militia are not worldly, but powerful in God to destroy fortresses.\" (2 Cor. 10:4)",
    "\"My grace is enough, because my power is perfected in weakness.\" (2 Cor. 12:9)",
    "\"He who boasts, glory in the Lord.\" (2 Cor. 10:17)",
    "\"Graise in this the one who praises himself: in understanding me and knowing me.\" (Jer. 9:24)",
    "\"By their fruits you will know them.\" (Matt. 7:16)",
    "\"Examine yourselves to see if you are in the faith.\" (2 Cor. 13:5)"
  ],
  "discussion": [
    "Read again 2 Corinthians 10:1-6. What is Paul's strategy for spiritual wars for truth, and how does it apply to ours without becoming judges of all?",
    "What can our local church do so that no one is deceived by false teachings, even if they come from within? How do we do it firmly and without destroying people?",
    "Why did Paul present a list of sufferings instead of a list of achievements? What does it mean in particular \"to glory in the Lord\" in your week?",
    "God didn't take Paul's thorn. What weakness have you asked God to take away from you, and what would change if instead of taking it away he held you in it?"
  ],
  "facilitator": [
    {
      "stationId": "muro",
      "apertura": "Why was the Corinthian church so impressed by polished teachers yet so reluctant to value Paul?",
      "seguimiento": "What argument has become entrenched in your thinking but has not yet been brought before the Word?",
      "ilustracion": "An ancient fortress fell wall by wall. An argument we have defended for years falls the same way.",
      "transicion": "If there are walls to tear down, let's talk about the weapons that can tear them down.",
      "actividad": "Invite each person to write, without signing the paper, one idea that needs to be examined in the light of the Bible.",
      "cierre": "Lord, bring down in us what rises against your knowledge."
    },
    {
      "stationId": "armas",
      "apertura": "How can someone be meek and brave at the same time, as Jesus was?",
      "seguimiento": "What happens in a church when there is only firmness? And when there is only kindness?",
      "ilustracion": "The same Jesus who said \"I am gentle and humble in heart\" overturned the temple tables. These were not two different versions of Jesus, but one consistent love.",
      "transicion": "Rivalry damages those weapons. Let's examine what we boast about.",
      "actividad": "Read 2 Corinthians 10:1-11 and underline the phrases where Paul is tender and those where he is firm.",
      "cierre": "Give us, Christ, your firmness with error and your tenderness with people."
    },
    {
      "stationId": "gloria",
      "apertura": "Why does Paul call comparing ourselves with one another unwise (2 Cor. 10:12)?",
      "seguimiento": "In what areas of church life does competition sneak in without us noticing?",
      "ilustracion": "Comparing is a race without a goal: there is always someone in front, and winning it does not give peace to anyone.",
      "transicion": "If the center is no longer us, let's learn to recognize a message that does not put the messenger in the center either.",
      "actividad": "Read Jeremiah 9:24 and answer in one sentence: what should a person rightly boast about?",
      "cierre": "May our only glory be to know you, Lord."
    },
    {
      "stationId": "discernir",
      "apertura": "Why does Paul compare the false teachers to the serpent that deceived Eve (2 Cor. 11:3)?",
      "seguimiento": "What practical signs help you distinguish a true message from one that is merely impressive?",
      "ilustracion": "Satan does not disguise himself as darkness: he disguises himself as an angel of light (2 Cor. 11:14). The deception always arrives well dressed.",
      "transicion": "Paul responded to the disguise by showing his scars. Let's look at what following Christ has cost us.",
      "actividad": "Make a short list of biblical criteria together to evaluate any new teaching.",
      "cierre": "Keep us, Lord, from every Gospel that is not yours."
    },
    {
      "stationId": "cicatriz",
      "apertura": "Why did Paul present scourges and shipwrecks instead of titles and achievements (2 Cor. 11:22-28)?",
      "seguimiento": "What has it cost you to follow Christ, and what did you learn from it?",
      "ilustracion": "Credentials are framed; scars are worn. Scars say more about a servant than credentials do.",
      "transicion": "Behind the scars was a thorn that God did not want to remove. Let's go there.",
      "actividad": "Read 2 Corinthians 11:23-28 aloud, then keep one minute of silence.",
      "cierre": "Thank you, Lord, because you see what it costs us when no one else notices."
    },
    {
      "stationId": "espina",
      "apertura": "Why didn't God take Paul's thorn even though he asked him three times?",
      "seguimiento": "What weakness do you hide for fear of what people at church would think?",
      "ilustracion": "A cracked clay vessel lets light through. This is why the treasure is placed in clay rather than gold (2 Cor. 4:7).",
      "transicion": "With the weakness in sight, let's take the exam that Paul asks for.",
      "actividad": "Let each one complete the phrase in silence: “Grace is enough for me today to…”.",
      "cierre": "Let your grace be enough, Lord, even where circumstances do not change."
    },
    {
      "stationId": "gracia",
      "apertura": "What does it mean to \"examine yourselves to see whether you are in the faith\" (2 Cor. 13:5)?",
      "seguimiento": "How can church discipline seek to restore rather than merely punish?",
      "ilustracion": "Paul went to Corinth a third time not to win a dispute, but to restore his people.",
      "transicion": "All this needs to land on something concrete for the next few days.",
      "actividad": "Read 2 Corinthians 13:7-9 and comment on what Paul asks in that prayer for the Church.",
      "cierre": "Restore us fully, Lord, and build us in your truth."
    },
    {
      "stationId": "paso",
      "apertura": "What is the difference between bringing our doctrines to the Bible and reading the Bible in light of our doctrines?",
      "seguimiento": "Who do you know who is listening to voices that draw them away from Christ, and how could you accompany them this week?",
      "ilustracion": "\"By putting ourselves to study the Word of God, we should do it with a humble heart\" (The Other Power, p. 31).",
      "transicion": "We close with a specific step and a name.",
      "actividad": "Share a step for this week and pray in pairs for the person you each mentioned.",
      "cierre": "Make us firm in your truth and tender with your people."
    }
  ],
  "patternTemplate": "{name}, you began by naming the wall inside you: {slot:muro|lower}. Then you stopped comparing yourself, learned to test what you hear, and climbed to the door to leave {slot:espina|lower} there. What once defended you is becoming a refuge, and you are not the one who built it.",
  "outOracion": "Lord, I come with the wall I carry inside: {slot:muro|lower}. You know that I also boast in {slot:gloria|lower}, and today I surrender it to you. Teach me to fight like Paul: firm with error and tender with people, testing what I hear through {slot:discernir|lower}. I leave {slot:espina|lower} at your door, and I will not hide it anymore. Hold me in {slot:gracia|lower}. Thank you that \"{verse}\" ({verseRef}). In Jesus' name, amen.",
  "outAliento": "{name}, you do not have to impress anyone for God to use you. You named the wall, brought {slot:espina|lower} into the light, and discovered that his grace is enough for you. You did not build the stronghold that remains; it was given to you, and this is why it will not fall.",
  "outAccion24": "In the next 24 hours I'm going to {slot:paso|lower}, and I'm going to measure what I hear by {slot:discernir|lower}.",
  "outPregunta": "This week I discovered that the fortress that had to be demolished was mine: {slot:muro|lower}. And I learned that his power is perfected in my weakness. What argument of yours needs to fall, and what weakness are you hiding?",
  "outTarjeta": "My stronghold this week: I tore down {slot:muro|lower}, stopped hiding {slot:espina|lower}, and found my support in {slot:gracia|lower}. Verse: \"{verse}\" ({verseRef})."
}
);
