import { makeLesson } from "../../engine/makeLesson.js";

/* Lesson 6 · Q3 2026 · 1 and 2 Corinthians
   Authored from the official quarterly, then adapted for this engine.
   Generated by scripts/build-lessons.mjs. Edit the draft, not this file. */
export default makeLesson(
{
  "number": 6,
  "slug": "dones-espirituales",
  "title": "Spiritual Gifts",
  "subtitle": "What if the body depends on the very part you think is unnecessary?",
  "kitName": "My Place in the Body",
  "artifactNoun": "place",
  "motif": "mosaico",
  "stages": [
    "sueltas",
    "borde",
    "encaje",
    "color",
    "entero"
  ],
  "stageLabels": [
    "Loose tiles · I feel unnecessary",
    "Border appears · I see the design",
    "My tile fits · I am needed",
    "Color enters · love unites",
    "Whole mosaic · one body"
  ],
  "verseRef": "1 Cor. 14:1",
  "verseText": "Follow the way of love and eagerly desire gifts of the Spirit, especially prophecy.",
  "promise": "In a few minutes you will find your place in the Body, {name}: you will name honestly how you feel in the church, recognize the gift the Spirit has already placed in your hands, see why members who seem weak are indispensable, and let love give meaning to everything you do. Tile by tile, what seemed loose will find its place.",
  "ui": {
    "start": "Begin finding my place",
    "emptyKit": "Your mosaic",
    "building": "Each answer places a tile",
    "buildingHint": "Touch the shining tile. You will see loose pieces become a single image.",
    "lastPiece": "A tile is missing",
    "patternLabel": "Your pattern in the mosaic",
    "doneTitle": "Your place is set",
    "doneSub": "No tile is left over in this design. Open it, save it, share it.",
    "open": "Open my mosaic",
    "back": "Back to my mosaic",
    "kitName": "My Place in the Body"
  },
  "slots": [
    {
      "id": "miembro",
      "n": 1,
      "label": "My place today",
      "teaser": "How I feel inside the church…",
      "icon": "people"
    },
    {
      "id": "don",
      "n": 2,
      "label": "The gift in my hands",
      "teaser": "What the Spirit already gave me...",
      "icon": "gift"
    },
    {
      "id": "indispensable",
      "n": 3,
      "label": "What seems weak",
      "teaser": "Why is my part necessary...",
      "icon": "hand"
    },
    {
      "id": "amor",
      "n": 4,
      "label": "The love that I practice",
      "teaser": "The phrase that gives meaning to everything...",
      "icon": "heart"
    },
    {
      "id": "ruido",
      "n": 5,
      "label": "Where my gift builds",
      "teaser": "Service that builds, not that sounds…",
      "icon": "voice"
    },
    {
      "id": "profecia",
      "n": 6,
      "label": "My word that lifts",
      "teaser": "Edify, exhort, console…",
      "icon": "scroll"
    },
    {
      "id": "encaje",
      "n": 7,
      "label": "My place confirmed",
      "teaser": "The truth in which I am left...",
      "icon": "anchor"
    },
    {
      "id": "paso",
      "n": 8,
      "label": "My step of the week",
      "teaser": "A concrete step and who do I invite…",
      "icon": "path"
    }
  ],
  "stations": [
    {
      "id": "miembro",
      "day": "Saturday · One body, many members",
      "tag": "Tile 1 · My place today",
      "title": "Where do you feel inside the body?",
      "story": "The church is one body with many members, each carrying a different function (1 Cor. 12:12). It sounds beautiful until you look at the image and cannot find your part. Something similar happened in Corinth: a few people shone, while the rest felt unnecessary. Before talking about gifts, Paul makes us look at the whole body. Begin by naming honestly where you see yourself.",
      "cue": "Before seeking your gift, {name}, be honest about where you see yourself today.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "Inside my church, today I feel...",
        "hint": "Choose the most sincere, not the most presentable",
        "saveLabel": "Save to my tile",
        "seedSub": "your place",
        "options": [
          {
            "id": "invisible",
            "label": "Invisible, as if no one would notice if I were gone",
            "insight": "Paul wrote this for you: “the members of the body that seem weakest are the most necessary” (1 Cor. 12:22). Just because others do not see what you do does not mean your work is not supporting them.",
            "tags": [
              "react:withdraw",
              "theme:self",
              "posture:avoidant"
            ]
          },
          {
            "id": "sobrante",
            "label": "Useful only for what no one wants to do",
            "insight": "What others leave behind is often what holds the house together. In the body there are no second-rate tasks, only distinct functions (1 Cor. 12:18).",
            "tags": [
              "theme:service",
              "posture:humble",
              "tone:raw"
            ]
          },
          {
            "id": "comparando",
            "label": "Always comparing myself to those who shine",
            "insight": "\"If the whole body were an eye, where would the ear be?\" (1 Cor. 12:17). Comparison robs you of the one part no one else can do: yours.",
            "tags": [
              "react:pride",
              "theme:humility",
              "tone:raw"
            ]
          },
          {
            "id": "cansado",
            "label": "Tired of serving without anyone seeing it",
            "insight": "God sees what the church agenda does not record. Serve, but let someone hold you up too: “we all need the help we can receive from others” (Ellen G. White, Lift Up Your Eyes, p. 139).",
            "tags": [
              "react:apathy",
              "theme:service",
              "tone:tender"
            ]
          },
          {
            "id": "buscando",
            "label": "Wanting to serve, but not knowing what",
            "insight": "Good sign. The gift does not appear while you analyze it; it appears when you take the first small step and someone is edified.",
            "tags": [
              "theme:hope",
              "posture:seeking",
              "tone:tender"
            ]
          },
          {
            "id": "colocado",
            "label": "In my place, and happy in it",
            "insight": "Guard it with gratitude and care. The gift that admires itself begins to make noise: “pursue gifts, pursuing love” (1 Cor. 14:1).",
            "tags": [
              "theme:service",
              "posture:surrendering",
              "tone:resolute"
            ]
          },
          {
            "id": "lejos",
            "label": "Far away, almost without participating anymore",
            "insight": "If you left because they made you feel like you were superfluous, that did not come from the Spirit. The body limps without you, even if it doesn't know how to tell you.",
            "tags": [
              "react:withdraw",
              "theme:unity",
              "posture:avoidant"
            ]
          }
        ]
      }
    },
    {
      "id": "don",
      "day": "Sunday · Diversity of gifts",
      "tag": "Tile 2 · The gift in my hands",
      "title": "The same Spirit distributes, and distributes differently",
      "story": "“There are diversities of gifts, but the Spirit is the same” (1 Cor. 12:4). Paul repeats the idea three times from three angles: gifts, ministries, and activities. Variety is not a disorder God merely tolerates. It springs from the character of a God who is Father, Son, and Spirit, three persons working together. And you already have the most basic gift if you confess that Jesus is Lord (1 Cor. 12:3). In the empire, that phrase could cost a person their life.",
      "cue": "{name}, the Spirit has already put something concrete in your hands. Dare to name it.",
      "module": {
        "type": "choiceInsight",
        "privacy": false,
        "prompt": "When I serve, what comes out best for me is…",
        "hint": "Think about what others are grateful for, not what you admire in others.",
        "saveLabel": "Save to my tile",
        "seedSub": "your gift",
        "closing": "The Spirit distributes “to each one individually as he wills” (1 Cor. 12:11). You did not ask for your gift nor did you choose it; it was entrusted to you. And if it was entrusted to you, it's because someone needs it.",
        "options": [
          {
            "id": "ensenar",
            "label": "Explain the Word clearly",
            "insight": "“To one is given the word of wisdom by the Spirit” (1 Cor. 12:8). Teaching well is a way of offering food; do it patiently, not to show off.",
            "tags": [
              "theme:word",
              "theme:truth",
              "posture:seeking"
            ]
          },
          {
            "id": "consolar",
            "label": "Listen and accompany those who suffer",
            "insight": "That is prophesying in Paul's sense: \"edification, exhortation, and consolation\" (1 Cor. 14:3). No one applauds it, and it sustains entire lives.",
            "tags": [
              "theme:love",
              "posture:humble",
              "tone:tender"
            ]
          },
          {
            "id": "sostener",
            "label": "Organize and hold what no one sees",
            "insight": "Paul calls these “helps” and “administrations” (1 Cor. 12:28), and he puts them on the same list as prophecy. Foundations may go unseen; without them, everything falls.",
            "tags": [
              "theme:service",
              "posture:humble",
              "tone:resolute"
            ]
          },
          {
            "id": "dar",
            "label": "Give generously without being noticed",
            "insight": "\"He who distributes, liberally\" (Rom. 12:8). A quiet gift, and the most difficult to fake.",
            "tags": [
              "theme:generosity",
              "posture:surrendering",
              "tone:resolute"
            ]
          },
          {
            "id": "orar",
            "label": "Pray consistently for specific names",
            "insight": "You may never know in this life how many people your faith sustained. Faith is one of the most basic and most underrated gifts (1 Cor. 12:9).",
            "tags": [
              "theme:prayer",
              "theme:faith",
              "tone:tender"
            ]
          },
          {
            "id": "hospedar",
            "label": "Receive people in my house and at my table",
            "insight": "“Be kind to one another without grumbling” (1 Pet. 4:9). An open table has reconciled more churches than many sermons.",
            "tags": [
              "theme:relationship",
              "theme:unity",
              "tone:tender"
            ]
          },
          {
            "id": "crear",
            "label": "Sing, play, or create for worship",
            "insight": "\"Another may have the gift of singing\" (Ellen G. White, Review and Herald, April 12, 1906). Art that points to God builds others up; art that points only to the artist is empty sound.",
            "tags": [
              "theme:service",
              "posture:seeking",
              "tone:resolute"
            ]
          },
          {
            "id": "hablar",
            "label": "Talk about Jesus to those who don't know him",
            "insight": "“Let men go out to work trusting in the Lord, and he will go with them” (Ellen G. White, Review and Herald, April 12, 1906). You don't go alone.",
            "tags": [
              "theme:mission",
              "posture:seeking",
              "tone:resolute"
            ]
          }
        ]
      }
    },
    {
      "id": "indispensable",
      "day": "Monday · Unity in diversity",
      "tag": "Tile 3 · What seems weak",
      "title": "What seems weak is what is necessary",
      "story": "\"Nor can the eye say to the hand, 'I have no need of you'\" (1 Cor. 12:21). The feet depend on the eyes to know where to go; the eyes cannot touch anything, but the hands can. Paul turns the whole logic of prestige on its head: the members who seem weakest turn out to be the most needed (1 Cor. 12:22). What you call \"little things\" may be carrying the body.",
      "cue": "Read this slowly and believe it this time, {name}.",
      "module": {
        "type": "perspectiveFlip",
        "saveLabel": "Save to my tile",
        "seedSub": "your necessary part",
        "prompt": "Touch each tile to see your part as God sees it",
        "hint": "Two looks at the same member of the body",
        "pairs": [
          {
            "see": "You think your part is so small that it doesn't count.",
            "sees": "“The members of the body that appear weakest are the most necessary” (1 Cor. 12:22)."
          },
          {
            "see": "You look at the one who has a visible gift and you cringe.",
            "sees": "\"If the whole body were an eye, where would the ear be?\" (1 Cor. 12:17). Without you, the body lacks meaning."
          },
          {
            "see": "You think that your place was chosen by discarding.",
            "sees": "“God placed each of the members in the body, just as he wanted” (1 Cor. 12:18). It wasn't chance or excess."
          },
          {
            "see": "You feel that your tiredness and your pain are yours alone.",
            "sees": "“If one member suffers, all the members suffer with it” (1 Cor. 12:26). Your pain is already a matter of the entire body."
          }
        ],
        "chooseLabel": "This is the truth that I needed",
        "teach": "In the body no one is self-sufficient and no one is expendable. The feeling that some members are worth more is just that: an impression (1 Cor. 12:22-23). That is why Paul, to cure contempt and envy at the same time, points out “an even more excellent way” (1 Cor. 12:31).",
        "commit": {
          "prompt": "Write who in your church you are going to tell this week that you do need it",
          "hint": "One sentence is enough, and it can last for years.",
          "placeholder": "I'm going to tell...",
          "extraKey": "teNecesito",
          "shareable": true
        }
      }
    },
    {
      "id": "amor",
      "day": "Tuesday · A more excellent path",
      "tag": "Tile 4 · The love I practice",
      "title": "Without love, the best gift sounds like metal",
      "story": "Between the chapter on gifts and the chapter on disorder, Paul places the chapter on love. It is not a poetic interlude: it is the key. Without love, the brightest tongue remains “a resounding metal” (1 Cor. 13:1), and faith that can move mountains is nothing (1 Cor. 13:2). The fifteen verbs in 1 Corinthians 13:4-7 make one thing clear: love is not so much something you feel as something you practice.",
      "cue": "Everything else is decided here, {name}.",
      "module": {
        "type": "pickReveal",
        "saveLabel": "Save to my tile",
        "seedSub": "your love practiced",
        "prompt": "Which of these love phrases do you miss the most when you serve?",
        "hint": "Touch each one and stay with the one that bothers you.",
        "chooseLabel": "This is what I am going to practice",
        "closing": "“Love is not one gift among many; it is the means through which all gifts reach their ultimate purpose” (Carl P. Cosaert, Andrews Bible Commentary, vol. 2, p. 543). That is why Paul places love in the middle of the conflict, not after it.",
        "allowCustom": {
          "label": "write mine",
          "placeholder": "The love that is most difficult for me to practice is…",
          "extraKey": "amorPropio"
        },
        "items": [
          {
            "t": "Love does not envy",
            "ref": "1 Cor. 13:4",
            "meaning": "Envy looks at the other's gift and feels that its own has shrunk. It's a lie: in a body, what the other can do also works for you."
          },
          {
            "t": "Love is not boastful or proud",
            "ref": "1 Cor. 13:4",
            "meaning": "A gift that needs an audience is no longer service. Corinth loved what was flashy; Paul asks for what is useful."
          },
          {
            "t": "Love does not insist on its own way",
            "ref": "1 Cor. 13:5",
            "meaning": "The question is no longer “what place do I belong?” and it becomes \"who is built?\""
          },
          {
            "t": "Love bears all things",
            "ref": "1 Cor. 13:7",
            "meaning": "Serving in a real church includes difficult people and thanks that never come. Love remains the same, without keeping score."
          }
        ]
      }
    },
    {
      "id": "ruido",
      "day": "Wednesday · The gift of tongues",
      "tag": "Tile 5 · Where my gift builds",
      "title": "Does this build up, or merely make noise?",
      "story": "The gift of tongues is the Spirit-given ability to speak languages you did not learn (Acts 2:1-13). Paul does not criticize the gift; he criticizes the inflated value the Corinthians placed on it, to the point of neglecting prophecy. If no one interprets, no one understands, and the service fills with confusion (1 Cor. 14:9, 23). His question was never \"How impressive does it sound?\" but \"Whom does it help?\"",
      "cue": "Train your ears with me for a moment, {name}.",
      "module": {
        "type": "skillThenCommit",
        "saveLabel": "Save to my tile",
        "seedSub": "your building",
        "skill": {
          "prompt": "Classify: does this edify the body, or does it just make noise?",
          "hint": "Paul's criterion is simple: was anyone left standing afterwards?",
          "badge": "You are learning to distinguish service from spectacle",
          "cats": [
            "Edifies the body",
            "It just makes noise"
          ],
          "rounds": [
            {
              "t": "\"I speak in a language that no one in the room understands, and no one interprets it.\"",
              "a": 1,
              "fb": "It only makes noise: \"if I do not know the value of words, I will be like a stranger\" (1 Cor. 14:11). That is why Paul asks for interpretation (1 Cor. 14:13, 27)."
            },
            {
              "t": "“I translate the sermon for the sister who has just arrived in the country.”",
              "a": 0,
              "fb": "Edifies: the language fulfills its function when it builds a bridge. That was exactly the gift at Pentecost (Acts 2:6-8)."
            },
            {
              "t": "\"I tell my spiritual experience so that you can see how much I have advanced.\"",
              "a": 1,
              "fb": "It only makes noise: “love does not boast” (1 Cor. 13:4). The gift that is exhibited stops serving at that very moment."
            },
            {
              "t": "\"I write to someone who is about to give up and I encourage them with the Word.\"",
              "a": 0,
              "fb": "Edify: that is prophesying according to Paul, “edification, exhortation and consolation” (1 Cor. 14:3)."
            },
            {
              "t": "\"I correct in public those who serve in a way different from mine.\"",
              "a": 1,
              "fb": "It only makes noise: “love does not behave rudely” (1 Cor. 13:5). A different function is not a wrong function."
            },
            {
              "t": "\"I carefully prepare something simple that others need, even if no one appreciates it.\"",
              "a": 0,
              "fb": "It edifies: “let no one despise the supposedly lesser gifts” (Ellen G. White, Review and Herald, April 12, 1906)."
            }
          ],
          "summary": "The gift is not measured by brilliance, but by what it leaves standing. “Let everything be done for edification” (1 Cor. 14:26). A small and understandable gift builds more than a spectacular one that no one understands."
        },
        "commit": {
          "prompt": "Where will your gift be built this week?",
          "hint": "Concrete, close, this week and not someday",
          "placeholder": "accompanying…, serving in…",
          "extraKey": "edificacion",
          "options": [
            "Visiting someone who no one visits anymore",
            "Serving behind the scenes in worship",
            "Teaching the children of my church",
            "Accompanying someone new until they feel at home",
            "Silently helping those who are overwhelmed"
          ]
        }
      }
    },
    {
      "id": "profecia",
      "day": "Thursday · The gift of prophecy",
      "tag": "Tile 6 · My word that lifts",
      "title": "To prophesy is to speak so others can stand",
      "story": "\"The one who prophesies speaks to people for edification, exhortation, and consolation\" (1 Cor. 14:3). Prophesying is not primarily about telling the future: it is speaking on behalf of God so that someone can live today. Judas and Silas were called prophets because they comforted and strengthened the believers at length (Acts 15:32). And these gifts did not fade away with the apostles: they continue to the end (Eph. 4:11-13).",
      "cue": "Someone is going to need to hear you this week, {name}.",
      "module": {
        "type": "choiceInsight",
        "privacy": false,
        "prompt": "This week, with my word I want…",
        "hint": "Choose what the Body needs from you right now",
        "saveLabel": "Save to my tile",
        "seedSub": "your word",
        "closing": "When someone claims to speak on behalf of God, the Bible asks for four tests: whether the prediction is fulfilled (Deut. 18:22), whether the message agrees with previous prophets (Isa. 8:20), whether the person's life confesses Christ (1 John 4:1-3), and whether their fruit supports the claim (Matt. 7:15-20). That is why we believe this gift was manifested in Ellen White, and why the remnant bears it as a sign (Rev. 12:17; 19:10).",
        "options": [
          {
            "id": "edificar",
            "label": "Uplift someone who feels worthless",
            "insight": "Tell them what they do and why it matters. Many leave the church not because of doctrine, but because no one told them they were needed.",
            "tags": [
              "theme:service",
              "theme:unity",
              "tone:tender"
            ]
          },
          {
            "id": "exhortar",
            "label": "Truly exhort those who are going astray",
            "insight": "Exhortation without love is harshness; love without truth is abandonment. Paul asks us to hold both together (1 Cor. 13:6).",
            "tags": [
              "theme:truth",
              "posture:humble",
              "tone:resolute"
            ]
          },
          {
            "id": "consolar",
            "label": "Console someone who has just suffered a great loss",
            "insight": "There is no need to explain away the pain. \"If one member suffers, all the members suffer with it\" (1 Cor. 12:26). Sometimes it is enough to stay close.",
            "tags": [
              "theme:love",
              "posture:humble",
              "tone:tender"
            ]
          },
          {
            "id": "confirmar",
            "label": "Encourage and strengthen other believers",
            "insight": "That's what Judas and Silas did (Acts 15:32). Sometimes prophesying is patiently repeating what people already know but stopped believing.",
            "tags": [
              "theme:word",
              "theme:faith",
              "tone:resolute"
            ]
          },
          {
            "id": "recibir",
            "label": "Receive the advice that I have been avoiding",
            "insight": "The gift of prophecy is also exercised by listening. If biblical advice has been bothering you for months, that discomfort has a name.",
            "tags": [
              "react:doubt",
              "theme:humility",
              "posture:humble"
            ]
          },
          {
            "id": "escuchar",
            "label": "Really listen before you speak",
            "insight": "The word you offer usually begins with a question. A person who does not listen gives advice for a problem that does not exist.",
            "tags": [
              "theme:humility",
              "posture:seeking",
              "tone:tender"
            ]
          }
        ]
      }
    },
    {
      "id": "encaje",
      "day": "The whole body, well concerted",
      "tag": "Tile 7 · My place confirmed",
      "title": "God placed you where he wanted",
      "story": "Gather what you already put in: what you felt, the gift you have, the part you thought was weak, the love you are going to practice and the place where you are going to build. All of this rests on a single decision that you did not make: God distributed, God placed, God sustains. Your place does not depend on someone approving it. It depends on who assigned it.",
      "cue": "{name}, this is what holds your place on the days when you doubt.",
      "module": {
        "type": "anchorChain",
        "saveLabel": "Receive my place and save",
        "seedSub": "your place",
        "prompt": "What truth about your place will you be left with?",
        "hint": "The one you will need to remember when you feel superfluous",
        "options": [
          "That God chose my place, not chance",
          "That my gift exists for the benefit of others",
          "That what seems weak is the most necessary",
          "That no one in the body can tell me: I don't need you",
          "May love, and not applause, measure my service"
        ],
        "allowCustom": {
          "placeholder": "I am left with the truth that…",
          "extraKey": "encajePropio"
        },
        "chain": [
          {
            "word": "The Spirit gave me a gift, not an ornament",
            "line": "\"To each one is given the manifestation of the Spirit for profit\" (1 Cor. 12:7). For the benefit of others, and that is why it matters."
          },
          {
            "word": "God chose my place in the body",
            "line": "“God placed each of the members in the body, just as he wanted” (1 Cor. 12:18). You didn't get here by chance."
          },
          {
            "word": "What seems weak turns out to be necessary",
            "line": "“The members that appear weakest are the most needed” (1 Cor. 12:22). The body rests where no one is looking."
          },
          {
            "word": "Love sustains what gift builds",
            "line": "“Now faith, hope and love remain; but the greatest of these is love” (1 Cor. 13:13)."
          }
        ],
        "climax": "The chain is complete."
      }
    },
    {
      "id": "paso",
      "day": "Friday · To study and meditate",
      "tag": "Tile 8 · My step of the week",
      "title": "With humility, do what you can",
      "story": "“Let no one belittle the supposedly minor gifts. Let everyone get to work. Let no one cross his arms in disbelief because he thinks he cannot do powerful works. Stop looking at yourselves. Look at your Leader. In humility, sincerity, and love, do what you can” (Ellen G. White, Review and Herald, April 12, 1906). You do not lack a better gift. You need to begin, and you need someone to begin with.",
      "cue": "Just one step, {name}, one you can take tomorrow.",
      "module": {
        "type": "commitDuo",
        "saveLabel": "Close my mosaic",
        "seedSub": "your step",
        "stepPrompt": "My specific step this week",
        "stepHint": "Tap an idea or write your own",
        "stepOptions": [
          "Offer my gift to whoever coordinates in my church",
          "Serve once without telling anyone it was me",
          "Write to someone who feels invisible",
          "Return to a ministry I abandoned",
          "Ask a brother what he needs from me"
        ],
        "stepPlaceholder": "my specific step...",
        "stepExtraKey": "pasoTexto",
        "personPrompt": "Someone I'm going to tell that their part is necessary",
        "personHint": "Think about the one who always serves and never appears on the show",
        "personPlaceholder": "a name...",
        "personExtraKey": "compartir"
      }
    }
  ],
  "encourage": [
    "“Follow love, and seek spiritual gifts, but above all, prophesy.” (1 Cor. 14:1)",
    "“To each one is given the manifestation of the Spirit for profit.” (1 Cor. 12:7)",
    "“The body is one, and has many members; but all the members, being many, are one body.” (1 Cor. 12:12)",
    "“The members of the body that seem weakest are the most necessary.” (1 Cor. 12:22)",
    "“The one who prophesies speaks to people for edification, exhortation and consolation.” (1 Cor. 14:3)",
    "“Now faith, hope and love remain, these three; but the greatest of them is love.” (1 Cor. 13:13)"
  ],
  "discussion": [
    "Reflect on the gift of prophecy. Why does Paul consider it more important than tongues when they are not interpreted? If necessary, read 1 Corinthians 14 again and follow its arguments.",
    "Discuss the life and ministry of Ellen White. Why do we believe that the prophetic gift was manifested in her? What concrete blessings has the church received and what challenges do we have to make better use of that gift?",
    "Think of several people who love you. How do you know their love is genuine? What does that tell you about why Paul talked so much about righteous love in the midst of his teaching about the gifts?",
    "As important as love is, why can't it be the only criterion for judging whether someone is telling the truth and deserves to be heard?"
  ],
  "facilitator": [
    {
      "stationId": "miembro",
      "apertura": "If the church is a body, what part do you feel you are, and why?",
      "seguimiento": "Have you ever felt like you were left out at church? How did it make you feel?",
      "ilustracion": "A mosaic seen up close is just loose, twisted pebbles. The image appears when you look at the whole, and no piece is left over.",
      "transicion": "If we are all part of the same body, let's see what the Spirit has given each person.",
      "actividad": "Let each one say, in a word, what part of the body they feel they are today.",
      "cierre": "Lord, give us eyes to see ourselves inside your body and not outside of it."
    },
    {
      "stationId": "don",
      "apertura": "Paul repeats “various” in 1 Corinthians 12:4-6. Why does he emphasize variety so strongly?",
      "seguimiento": "Read the lists in 1 Corinthians 12:8-10 and 28, Romans 12:6-8, and Ephesians 4:11. What do you think is your gift?",
      "ilustracion": "Gifts, ministries and activities are three angles of the same thing: Spirit, Lord and God working in one body.",
      "transicion": "If the Spirit gives something different to each person, then everyone needs the others.",
      "actividad": "Let each person name out loud a gift they see in the person sitting next to them.",
      "cierre": "Thank you, Holy Spirit, for giving to each person as you choose and leaving no one empty."
    },
    {
      "stationId": "indispensable",
      "apertura": "Why is the image of a body so appropriate for describing the church?",
      "seguimiento": "Which members of our congregation do something necessary that we rarely acknowledge?",
      "ilustracion": "The feet depend on the eyes to know where to go; the eyes cannot touch anything, but the hands can.",
      "transicion": "If no one is unnecessary, something must guide the use of every gift: love.",
      "actividad": "Read 1 Corinthians 12:14-26 and write down each phrase that denies that someone is expendable.",
      "cierre": "Teach us, Lord, not to despise what you called necessary."
    },
    {
      "stationId": "amor",
      "apertura": "Why does Paul place the chapter on love right between the two chapters on the gifts?",
      "seguimiento": "Of the fifteen verbs in 1 Corinthians 13:4-7, which do you find most difficult when serving alongside others?",
      "ilustracion": "Love is not just another gift on the list; it is the means by which all gifts achieve their purpose.",
      "transicion": "With that criterion in hand, let's examine the gift that caused the most problems in Corinth.",
      "actividad": "Hand out the fifteen verbs and have each one explain theirs with an example from real life.",
      "cierre": "May our service, Lord, never be resounding metal."
    },
    {
      "stationId": "ruido",
      "apertura": "What exactly was the gift of tongues according to Acts 2 and 1 Corinthians 14?",
      "seguimiento": "Why does Paul insist so much on interpretation and everyone understanding?",
      "ilustracion": "A gift without interpretation is like a tuned instrument playing alone in an empty room: it impresses no one and edifies no one.",
      "transicion": "From the gift that Corinth overvalued we move on to the one it neglected: prophecy.",
      "actividad": "Read 1 Corinthians 14:5, 13, 26-27 and make a list of the practical rules that Paul gives.",
      "cierre": "May everything we do, Lord, be for edification and not for show."
    },
    {
      "stationId": "profecia",
      "apertura": "According to 1 Corinthians 14:3, what is the purpose of the gift of prophecy?",
      "seguimiento": "What are the four biblical tests to evaluate someone who claims to speak for God?",
      "ilustracion": "Judas and Silas were called prophets, and their prophecy consisted of comforting and strengthening the believers at length.",
      "transicion": "If these gifts continue to the end, everyone needs to know where theirs fits.",
      "actividad": "Discuss Ephesians 4:11-13 and answer: how long do the gifts remain, and what purpose do they serve?",
      "cierre": "Thank you, Lord, for still speaking to us and for giving us something to recognize your voice."
    },
    {
      "stationId": "encaje",
      "apertura": "What changes in your week if you truly believe that God placed you where you are?",
      "seguimiento": "What truth from 1 Corinthians 12 do you need to remember on days when you feel worthless?",
      "ilustracion": "A single tile looks like a color error. Put in place, it is the exact shadow that was needed.",
      "transicion": "Once the place is confirmed, let's take a concrete step for the next few days.",
      "actividad": "Recite 1 Corinthians 12:18 together and have each one complete: \"God placed me here to...\".",
      "cierre": "We confirm today the place you gave us, and we accept it with gratitude."
    },
    {
      "stationId": "paso",
      "apertura": "\"Let no one cross their arms in disbelief.\" What paralyzes us when it comes to serving?",
      "seguimiento": "Who in this church should we tell this week that their part is needed?",
      "ilustracion": "Ellen White asks us to stop looking at ourselves and look at our Leader, and do what we can with meekness.",
      "transicion": "Let's close by putting together the complete mosaic: a gift, a place and a step.",
      "actividad": "Share a specific step for this week and the name of the person you are going to encourage.",
      "cierre": "Let us work, Lord, holding hands and under a single authority."
    }
  ],
  "patternTemplate": "{name}, you named how you feel inside the church: “{slot:miembro}”. Yet the Spirit had already entrusted this gift to you: “{slot:don}”. You chose to practice the love that says “{slot:amor}”, and you found where your gift can build others up: “{slot:ruido}”. The tile that seemed loose has clicked into place, and the image is beginning to appear.",
  "outOracion": "Lord, I do not hide how I have felt within your church: “{slot:miembro}”. Thank you that your Spirit has already placed a gift in my hands: “{slot:don}”. Teach me to use it with love, and remind me especially that “{slot:amor}”. I want my gift to build others up by {slot:ruido|lower}, and this week I want to {slot:profecia|lower}. I hold on to this truth: “{slot:encaje}”. Forgive my envy of other people's gifts and my contempt for my own. Thank you because “{verse}” ({verseRef}). In the name of Jesus, amen.",
  "outAliento": "{name}, you are not a loose tile or a spare part someone forgot to return. God placed every member in the body as he chose, and he entrusted this gift to you: “{slot:don}”. What you call small, Paul calls necessary. You held on to this truth: “{slot:encaje}”. Serve with love even if no one applauds; the whole body rests on parts that no one sees.",
  "outAccion24": "In the next 24 hours I will {slot:paso|lower}, and I will put my gift to work by {slot:ruido|lower}.",
  "outPregunta": "This week I named how I have felt within the church: “{slot:miembro}”. I also discovered that the members who seem weakest are indispensable. What do you think your gift is, and who once made you feel unnecessary?",
  "outTarjeta": "My place in the Body: the Spirit entrusted this gift to me: “{slot:don}”. I will use it with love by {slot:ruido|lower}, and I will hold on to this truth: “{slot:encaje}”.\nVerse: “{verse}” ({verseRef})."
}
);
