import { makeLesson } from "../engine/makeLesson.js";

/* Lección 4 · Q3 2026 · 1 y 2 Corintios
   Authored from the official quarterly, then adapted for this engine.
   Generated by scripts/build-lessons.mjs. Edit the draft, not this file. */
export default makeLesson(
{
  "number": 4,
  "slug": "tu-cuerpo-su-templo",
  "title": "Tu Cuerpo, Su Templo",
  "subtitle": "¿Qué has aprendido a tolerar sin darte cuenta?",
  "kitName": "Mi Templo",
  "artifactNoun": "templo",
  "motif": "barro",
  "stages": [
    "grieta",
    "arcilla",
    "torno",
    "horno",
    "templo"
  ],
  "stageLabels": [
    "Barro agrietado · lo que callo",
    "Arcilla en sus manos · me miro de frente",
    "En el torno · dejo que me forme",
    "Pasa por el fuego · sano y me firmo",
    "Templo habitado · comprado por precio"
  ],
  "verseRef": "1 Cor. 6:19-20",
  "verseText": "¿No saben que su cuerpo es templo del Espíritu Santo, que está en ustedes, que tienen de Dios, y que no son suyos?",
  "promise": "En unos minutos vas a levantar tu Templo, {name}: nombrarás lo que se te fue metiendo sin permiso, mirarás sin miedo lo que aprendiste a tolerar, aprenderás a distinguir la corrección que sana de la que destruye, y terminarás sosteniéndote en la única frase que lo cambia todo: fuiste comprado por precio. Pieza a pieza, el barro agrietado va tomando forma de templo.",
  "ui": {
    "start": "Empezar a levantar mi templo",
    "emptyKit": "Tu templo",
    "building": "Cada respuesta asienta una piedra",
    "buildingHint": "Toca la pieza que brilla. Verás el barro agrietado tomar forma hasta ser templo.",
    "lastPiece": "Falta una pieza",
    "patternLabel": "Tu patrón en el barro",
    "doneTitle": "Tu templo está en pie",
    "doneSub": "No lo levantaste solo. Ábrelo, guárdalo, compártelo.",
    "open": "Abrir mi templo",
    "back": "Volver a mi templo",
    "kitName": "Mi Templo"
  },
  "slots": [
    {
      "id": "influencia",
      "n": 1,
      "label": "Lo que me va formando",
      "teaser": "Lo que entra sin que yo lo decida…",
      "icon": "cloud"
    },
    {
      "id": "tolerancia",
      "n": 2,
      "label": "Lo que dejo pasar",
      "teaser": "Lo que hago con lo que sé que no está bien…",
      "icon": "eye"
    },
    {
      "id": "restauracion",
      "n": 3,
      "label": "Mi paso hacia la restauración",
      "teaser": "La corrección que llevo tiempo esquivando…",
      "icon": "hand"
    },
    {
      "id": "pleito",
      "n": 4,
      "label": "El pleito que dejo de alimentar",
      "teaser": "Lo que quiero resolver en la mesa correcta…",
      "icon": "path"
    },
    {
      "id": "pertenencia",
      "n": 5,
      "label": "Mi cuerpo, no mío",
      "teaser": "Cómo trataré lo que le pertenece a él…",
      "icon": "heart"
    },
    {
      "id": "huida",
      "n": 6,
      "label": "De lo que voy a huir",
      "teaser": "Lo que José me enseñó a dejar atrás…",
      "icon": "flame"
    },
    {
      "id": "precio",
      "n": 7,
      "label": "La verdad que me sostiene",
      "teaser": "Fui comprado por precio…",
      "icon": "anchor"
    },
    {
      "id": "paso",
      "n": 8,
      "label": "Mi paso de la semana",
      "teaser": "Un paso concreto y alguien que camine conmigo…",
      "icon": "sun"
    }
  ],
  "stations": [
    {
      "id": "influencia",
      "day": "Sábado · Lo que entra sin permiso",
      "tag": "Pieza 1 · Lo que me va formando",
      "title": "Todo lo que entra deja huella",
      "story": "Tu mente se parece a una esponja: lo que pasa por tus ojos y tus oídos no desaparece, aunque no lo recuerdes. Sigue ahí, influyendo despacio en lo que piensas, sientes y haces. Así fue en Corinto. Después de rogarles que dejaran las divisiones (1 Cor. 1 al 4), Pablo tuvo que hablar de inmoralidad, de pleitos y de matrimonio (1 Cor. 5 al 7), porque las normas de la ciudad se habían mudado adentro de la iglesia sin que nadie firmara la entrada.",
      "cue": "Antes de avanzar, {name}, mira sin prisa lo que ha estado entrando en ti.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "¿Qué influencia de tu entorno se te fue metiendo sin que lo decidieras?",
        "hint": "Nadie va a leer esto. Elige la más honesta",
        "saveLabel": "Guardar en mi templo",
        "seedSub": "lo que te forma",
        "closing": "Nombrarlo no es acusarte. Es abrir la puerta para que el Espíritu entre por donde tú mismo la abriste.",
        "options": [
          {
            "id": "pantallas",
            "label": "Las pantallas de la madrugada",
            "insight": "Lo que ves cansado se queda contigo despierto. No es debilidad de carácter, es puerta abierta a deshoras.",
            "tags": [
              "react:apathy",
              "theme:self",
              "posture:avoidant"
            ]
          },
          {
            "id": "humor",
            "label": "El humor que normaliza todo",
            "insight": "La risa es un maestro silencioso: nos enseña qué dejó de ser grave. Corinto también se acostumbró riendo.",
            "tags": [
              "theme:truth",
              "react:apathy",
              "tone:raw"
            ]
          },
          {
            "id": "prisa",
            "label": "La prisa que me deja sin oración",
            "insight": "Cuando el día empieza sin él, alguien más te habla primero. Y el primero que habla suele quedarse.",
            "tags": [
              "theme:prayer",
              "react:control",
              "posture:seeking"
            ]
          },
          {
            "id": "aprobacion",
            "label": "La necesidad de caer bien",
            "insight": "Muchos corintios querían la aprobación de su ciudad. Es un anhelo humano y hondo, pero decide más de lo que crees.",
            "tags": [
              "react:fear",
              "theme:relationship",
              "posture:clinging"
            ]
          },
          {
            "id": "cansancio",
            "label": "El cansancio que baja mis defensas",
            "insight": "Casi nunca caemos por convicción; caemos por agotamiento. Reconocerlo es sabiduría, no derrota.",
            "tags": [
              "theme:humility",
              "posture:humble",
              "tone:tender"
            ]
          },
          {
            "id": "voz",
            "label": "La voz que dice que ya nada importa",
            "insight": "Esa voz miente con calma. «No son suyos» (1 Cor. 6:19) significa justo lo contrario: importas tanto que fuiste pagado.",
            "tags": [
              "react:doubt",
              "theme:hope",
              "tone:raw"
            ]
          }
        ]
      }
    },
    {
      "id": "tolerancia",
      "day": "Domingo · Disonancia entre fe y práctica",
      "tag": "Pieza 2 · Lo que dejo pasar",
      "title": "Cuando lo tolerado se vuelve normal",
      "story": "Pablo se entera de algo que ni la ciudad pagana aprobaba: un hombre viviendo con la esposa de su padre (1 Cor. 5:1). Y lo que más le duele no es solo el pecado, sino la iglesia: en vez de dolerse, estaban orgullosos de lo tolerantes que eran (1 Cor. 5:2). Toleraban con nombre de amor lo que en realidad era ceguera. Pablo no escribe para hundirlos: «no escribo esto para avergonzarlos, sino para amonestarlos como a hijos míos amados» (1 Cor. 4:14).",
      "cue": "{name}, no hace falta que se lo cuentes a nadie. Solo míralo tú.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "¿Qué sueles hacer con lo que sabes que no está bien?",
        "hint": "En ti o a tu alrededor. Elige lo que de verdad haces",
        "saveLabel": "Guardar en mi templo",
        "seedSub": "lo que dejas pasar",
        "closing": "Que puedas nombrarlo ya es luz entrando. Y ojo con el otro extremo: la meta nunca fue tener razón, sino que alguien vuelva a casa.",
        "options": [
          {
            "id": "mirar",
            "label": "Mirar para otro lado",
            "insight": "Es lo más rápido y lo más caro. Lo que no se mira no se sana; solo se muda a un cuarto más adentro.",
            "tags": [
              "react:withdraw",
              "theme:truth",
              "posture:avoidant"
            ]
          },
          {
            "id": "justificar",
            "label": "Justificarlo, porque hoy todo se acepta",
            "insight": "Corinto tenía su versión de esa frase: «todo es permitido» (1 Cor. 6:12). Pablo no la niega, la completa: no todo edifica.",
            "tags": [
              "react:apathy",
              "theme:sin",
              "tone:raw"
            ]
          },
          {
            "id": "comentar",
            "label": "Comentarlo con otros, nunca con quien debo",
            "insight": "Hablar de alguien es fácil; hablar con alguien cuesta. Solo lo segundo restaura.",
            "tags": [
              "react:withdraw",
              "theme:unity",
              "tone:raw"
            ]
          },
          {
            "id": "dureza",
            "label": "Señalarlo con dureza",
            "insight": "La verdad sin ternura hiere sin curar. Pablo fue severo, sí, pero con la vista puesta en devolverlo a la mesa (2 Cor. 2:7).",
            "tags": [
              "react:pride",
              "theme:humility",
              "posture:proud"
            ]
          },
          {
            "id": "callar",
            "label": "Callar por miedo a perder a alguien",
            "insight": "Ese miedo nace de querer a la persona. Dios lo entiende. Pero el silencio que protege el vínculo a veces hunde a quien amas.",
            "tags": [
              "react:fear",
              "theme:relationship",
              "tone:tender"
            ]
          },
          {
            "id": "hablar",
            "label": "Hablarlo de frente y con cariño",
            "insight": "Eso es raro y costoso, y es exactamente lo que Pablo pedía. Sigue haciéndolo con las rodillas en el suelo.",
            "tags": [
              "theme:love",
              "posture:humble",
              "tone:resolute"
            ]
          }
        ]
      }
    },
    {
      "id": "restauracion",
      "day": "Lunes · Lidiando con lo difícil",
      "tag": "Pieza 3 · Mi paso hacia la restauración",
      "title": "La disciplina que apunta a sanar",
      "story": "Las palabras de Pablo suenan duras a oídos modernos: quitar de en medio, no juntarse, entregar a Satanás (1 Cor. 5:2, 5, 11). Pero lee el final de la frase: «a fin de que el espíritu sea salvo» (1 Cor. 5:5). La disciplina bíblica nunca fue un castigo con ánimo de humillar; es un tratamiento con ánimo de devolver. Tanto que después Pablo escribe: «deben perdonarlo y consolarlo» (2 Cor. 2:7). El proceso alcanza su meta el día en que la persona vuelve a sentarse a la mesa.",
      "cue": "Aquí conviene ir despacio, {name}. Esto no va de castigar a nadie.",
      "module": {
        "type": "skillThenCommit",
        "saveLabel": "Guardar en mi templo",
        "seedSub": "tu paso hacia la restauración",
        "skill": {
          "prompt": "Entrena el oído: ¿corrección que restaura, o castigo que destruye?",
          "hint": "Las dos suenan firmes. Solo una busca traerte de vuelta",
          "badge": "Estás aprendiendo a distinguir la corrección que sana",
          "cats": [
            "Corrección que restaura",
            "Castigo que destruye"
          ],
          "rounds": [
            {
              "t": "«Te digo esto porque quiero verte de vuelta en la mesa.»",
              "a": 0,
              "fb": "Restaura: el objetivo declarado es el regreso, no la expulsión definitiva (2 Cor. 2:7)."
            },
            {
              "t": "«Que todos se enteren de lo que hiciste.»",
              "a": 1,
              "fb": "Destruye: la exposición pública no era el método de Pablo. Él buscaba salvar, no exhibir."
            },
            {
              "t": "«Voy a hablar contigo primero, a solas.»",
              "a": 0,
              "fb": "Restaura: así enseñó Jesús a empezar (Mat. 18:15). Primero la persona, después el proceso."
            },
            {
              "t": "«Después de esto, ya no eres uno de nosotros.»",
              "a": 1,
              "fb": "Destruye: la disciplina bíblica es temporal y termina en abrazo, no en sentencia perpetua."
            },
            {
              "t": "«Vamos a acompañarte mientras sales de esto.»",
              "a": 0,
              "fb": "Restaura: nadie sale solo. La iglesia que corrige también carga (Gál. 6:1)."
            },
            {
              "t": "«Mejor ni lo mencionemos, no vaya a incomodar.»",
              "a": 1,
              "fb": "Destruye por omisión: era el error de Corinto. Callar dejó al hombre solo con su ruina."
            }
          ],
          "summary": "La corrección de Dios nunca termina en la puerta; termina en la mesa. «A fin de que el espíritu sea salvo» (1 Cor. 5:5) es la frase que ordena todo lo demás."
        },
        "commit": {
          "prompt": "¿Qué paso hacia la restauración llevas tiempo esquivando?",
          "hint": "Uno solo, del tamaño de esta semana",
          "placeholder": "el paso que vengo posponiendo es…",
          "extraKey": "pasoRestaurador",
          "options": [
            "Pedir perdón a quien vengo evitando",
            "Aceptar una corrección que ya me dieron",
            "Buscar a alguien que se alejó en silencio",
            "Hablar con mi pastor de algo que callo",
            "Volver a sentarme con quien dejé de hablar"
          ]
        }
      }
    },
    {
      "id": "pleito",
      "day": "Martes · Protegiendo la identidad",
      "tag": "Pieza 4 · El pleito que dejo de alimentar",
      "title": "Los trapos no se lavan afuera",
      "story": "Ahora aparecen creyentes demandándose entre sí ante los tribunales de la ciudad (1 Cor. 6:1). Pablo no discute el derecho civil: le duele la identidad de la familia. En los tribunales romanos solía ganar el de más rango, más dinero o más contactos. Y la iglesia, que un día juzgará con Cristo, no era capaz de sentarse a resolver lo suyo. Su pregunta sigue picando: ¿por qué no sufrir más bien el agravio antes que perder a un hermano (1 Cor. 6:7)?",
      "cue": "Piensa en un conflicto tuyo mientras lees, {name}, y no lo sueltes todavía.",
      "module": {
        "type": "pickReveal",
        "saveLabel": "Guardar en mi templo",
        "seedSub": "tu pleito",
        "prompt": "¿Cuál de estas cosas quieres dejar de hacer con tu conflicto?",
        "hint": "Toca cada una y quédate con la que te toca a ti",
        "chooseLabel": "Esto es lo que voy a dejar",
        "closing": "Ningún conflicto se resuelve en el tribunal equivocado. Llévalo a la mesa donde hay pan, oración y gente que te quiere de verdad.",
        "allowCustom": {
          "label": "Escribir el mío",
          "placeholder": "Con mi conflicto voy a dejar de…",
          "extraKey": "pleitoPropio"
        },
        "items": [
          {
            "t": "Llevar al hermano ante los de afuera",
            "ref": "1 Cor. 6:1",
            "meaning": "Lo que es de la familia se habla en la familia. Sacarlo fuera casi nunca busca justicia; busca aliados."
          },
          {
            "t": "Ganar el pleito y perder al hermano",
            "ref": "1 Cor. 6:7",
            "meaning": "«¿Por qué no sufren más bien el agravio?» Hay victorias que salen carísimas: cuestan una relación."
          },
          {
            "t": "Hablarlo con todos menos con él",
            "ref": "Mat. 18:15",
            "meaning": "«Ve y repréndelo estando tú y él solos.» El orden de Jesús protege la dignidad del otro."
          },
          {
            "t": "Dejar que el más fuerte tenga razón",
            "ref": "Sant. 2:1-4",
            "meaning": "En Roma decidía el rango. Entre nosotros no: la fe «no debe tener acepción de personas»."
          }
        ]
      }
    },
    {
      "id": "pertenencia",
      "day": "Miércoles · El antídoto",
      "tag": "Pieza 5 · Mi cuerpo, no mío",
      "title": "Lavado, santificado, justificado",
      "story": "Algunos en Corinto razonaban así: el estómago es para la comida, así que el cuerpo es para el sexo (1 Cor. 6:13). Pablo responde con tres verdades que cambian la ecuación. Primera: «ya han sido lavados, ya han sido santificados, ya han sido justificados» (1 Cor. 6:11); ese ya está hecho. Segunda: somos miembros de Cristo, unidos a él (1 Cor. 6:15, 17). Tercera: tu cuerpo es templo del Espíritu (1 Cor. 6:19). No te libera para pecar; te liberó del pecado. Quién eres decide qué haces.",
      "cue": "Deja que estas cartas te devuelvan la mirada de Dios, {name}.",
      "module": {
        "type": "perspectiveFlip",
        "saveLabel": "Guardar en mi templo",
        "seedSub": "tu pertenencia",
        "prompt": "Toca cada carta para ver tu cuerpo como Dios lo ve",
        "hint": "Dos maneras de mirar la misma vida",
        "pairs": [
          {
            "see": "Sientes que tu cuerpo es solo tuyo y haces con él lo que quieras.",
            "sees": "«No son suyos, porque han sido comprados por precio» (1 Cor. 6:19-20). Pertenecer no es perder libertad, es tener dueño que te ama."
          },
          {
            "see": "Cargas la lista de lo que fuiste y crees que ese es tu nombre.",
            "sees": "«Ya han sido lavados, ya han sido santificados» (1 Cor. 6:11). Ese ya de Dios llegó antes que tu esfuerzo."
          },
          {
            "see": "Piensas que la libertad cristiana significa que da igual lo que hagas.",
            "sees": "Fuiste liberado del pecado, no para él (Rom. 6:18). La gracia no cancela el diseño, lo restaura."
          },
          {
            "see": "Ves tu cuerpo como un problema que hay que vigilar.",
            "sees": "Es «templo del Espíritu Santo» (1 Cor. 6:19). Dios no vigila desde afuera: escogió vivir dentro."
          }
        ],
        "chooseLabel": "Esta es la verdad que necesitaba",
        "teach": "Huir de la inmoralidad no se logra apretando los dientes. Se logra desde adentro: unido a Cristo (1 Cor. 6:17), habitado por su Espíritu (1 Cor. 6:19), presentando el cuerpo como «sacrificio vivo, santo, agradable a Dios» (Rom. 12:1).",
        "commit": {
          "prompt": "Escribe cómo vas a tratar esta semana lo que le pertenece a él",
          "hint": "Concreto y pequeño vale más que solemne y vago",
          "placeholder": "Voy a tratar mi cuerpo como…",
          "extraKey": "pertenenciaTexto",
          "shareable": true
        }
      }
    },
    {
      "id": "huida",
      "day": "Jueves · Huir, como José",
      "tag": "Pieza 6 · De lo que voy a huir",
      "title": "Correr también es fidelidad",
      "story": "Cuando la esposa de Potifar insistió, José no debatió: «huyó y salió» (Gén. 39:12). No fue cobardía, fue lucidez. Hay batallas que se ganan lejos del campo. Por eso Pablo escribe «huyan de la inmoralidad sexual» (1 Cor. 6:18) justo entre dos verdades enormes: estás unido al Señor y eres templo de su Espíritu. Y en el capítulo siguiente habla del matrimonio y de la soltería con una naturalidad que la iglesia a veces ha perdido: de esto se puede hablar, y hay que hablar.",
      "cue": "{name}, elige algo real, no lo más presentable.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "¿De qué necesitas huir esta semana, como huyó José?",
        "hint": "Solo tú y Dios leen esto. Sé concreto",
        "saveLabel": "Guardar en mi templo",
        "seedSub": "tu huida",
        "closing": "Huir no es tener miedo: es saber dónde no puedes quedarte. Y no huyes solo, huyes hacia Alguien que ya vive en ti.",
        "options": [
          {
            "id": "conversacion",
            "label": "Una conversación que ya cruzó la línea",
            "insight": "Casi siempre empieza siendo inocente y termina siendo secreta. El secreto es el aviso.",
            "tags": [
              "react:withdraw",
              "theme:truth",
              "tone:raw"
            ]
          },
          {
            "id": "noche",
            "label": "Lo que abro cuando estoy solo de noche",
            "insight": "Ahí no falla la voluntad, falla la estrategia. José no resistió en la habitación: salió de ella.",
            "tags": [
              "theme:self",
              "posture:humble",
              "tone:raw"
            ]
          },
          {
            "id": "amistad",
            "label": "Una amistad que se volvió otra cosa",
            "insight": "Nombrarlo duele porque hay cariño real. Pero la honestidad ahora ahorra un daño mucho mayor después.",
            "tags": [
              "react:fear",
              "theme:relationship",
              "tone:tender"
            ]
          },
          {
            "id": "vacio",
            "label": "El vacío que lleno con cualquier cosa",
            "insight": "Debajo del hábito casi siempre hay hambre de compañía. Llévale a él el hambre, no solo el hábito.",
            "tags": [
              "theme:hope",
              "posture:seeking",
              "tone:tender"
            ]
          },
          {
            "id": "imagen",
            "label": "Una imagen que vuelve a mi mente",
            "insight": "Que vuelva no es tu condena. Tú decides si le abres la puerta o la entregas en oración.",
            "tags": [
              "react:doubt",
              "theme:grace",
              "posture:surrendering"
            ]
          },
          {
            "id": "soledad",
            "label": "La soledad que no le cuento a nadie",
            "insight": "El aislamiento es terreno fértil. Un solo amigo que sepa la verdad cambia toda tu semana.",
            "tags": [
              "react:withdraw",
              "theme:service",
              "posture:seeking"
            ]
          }
        ]
      }
    },
    {
      "id": "precio",
      "day": "Comprados por precio",
      "tag": "Pieza 7 · La verdad que me sostiene",
      "title": "No eres tuyo, y esa es la buena noticia",
      "story": "Reúne lo que has puesto aquí: lo que entraba sin permiso, lo que dejabas pasar, el paso que estabas esquivando, el pleito, tu cuerpo, tu huida. Todo cuelga de una sola frase: «han sido comprados por precio» (1 Cor. 6:20). Antes de pedirte nada, Pablo te recuerda lo que ya eres. La ética cristiana no empieza en el esfuerzo, empieza en el rescate.",
      "cue": "Recíbelo despacio, {name}. Esto sostiene todo lo demás.",
      "module": {
        "type": "anchorChain",
        "saveLabel": "Recibirlo y guardar",
        "seedSub": "la verdad que te sostiene",
        "chain": [
          {
            "word": "Fuiste comprado",
            "line": "«Han sido comprados por precio» (1 Cor. 6:20). No te ganaste el lugar: alguien lo pagó."
          },
          {
            "word": "Fuiste lavado",
            "line": "«Ya han sido lavados, ya han sido santificados» (1 Cor. 6:11). Tu pasado ya no es tu nombre."
          },
          {
            "word": "Fuiste habitado",
            "line": "Tu cuerpo es «templo del Espíritu Santo» (1 Cor. 6:19). Él no te visita de vez en cuando: vive ahí."
          },
          {
            "word": "Fuiste restaurado",
            "line": "«Deben perdonarlo y consolarlo» (2 Cor. 2:7). Cuando Dios corrige, la última palabra es un abrazo."
          }
        ],
        "climax": "Por eso Pablo no discute contigo: te recuerda quién eres. «Glorifiquen a Dios en su cuerpo» (1 Cor. 6:20) no es una carga que te ponen encima; es lo que brota cuando entiendes que fuiste rescatado.",
        "prompt": "¿Cuál de estas verdades vas a sostener esta semana?",
        "hint": "La que más te cueste creer suele ser la que más necesitas",
        "options": [
          "Que fui comprado por precio",
          "Que ya fui lavado y no soy mi pasado",
          "Que su Espíritu vive dentro de mí",
          "Que la corrección de Dios termina en abrazo"
        ],
        "allowCustom": {
          "placeholder": "voy a sostenerme en que…",
          "extraKey": "precioPropio"
        }
      }
    },
    {
      "id": "paso",
      "day": "Viernes · Para estudiar y meditar",
      "tag": "Pieza 8 · Mi paso de la semana",
      "title": "Un paso, y alguien contigo",
      "story": "Elena G. de White escribió: «Cuando uno se vacía completamente de sí mismo, cuando todos los falsos dioses son expulsados del alma, el vacío es llenado por el Espíritu de Cristo» (The Home Missionary, noviembre de 1893, p. 29). No se trata de apretar más fuerte, sino de vaciar y dejar llenar. Y esto casi nunca se logra a solas: la iglesia existe para que nadie vuelva caminando sin compañía. Te falta una pieza, la más concreta de todas.",
      "cue": "Cierra con algo que puedas hacer mañana mismo, {name}.",
      "module": {
        "type": "commitDuo",
        "saveLabel": "Cerrar mi templo",
        "seedSub": "tu paso",
        "stepPrompt": "Mi paso concreto de esta semana",
        "stepHint": "Toca una idea o escribe la tuya",
        "stepOptions": [
          "Cerrar la puerta por la que entra lo que me daña",
          "Buscar a la persona con la que tengo el pleito",
          "Contarle a alguien de confianza lo que callo",
          "Empezar el día orando antes de tomar el teléfono",
          "Escribir en mi Biblia que fui comprado por precio"
        ],
        "stepPlaceholder": "mi paso concreto…",
        "stepExtraKey": "pasoTexto",
        "personPrompt": "Alguien que camine conmigo esta semana",
        "personHint": "No un juez, un compañero. ¿Quién puede ser?",
        "personPlaceholder": "un nombre…",
        "personExtraKey": "compania"
      }
    }
  ],
  "encourage": [
    "«¿No saben que su cuerpo es templo del Espíritu Santo, que está en ustedes, que tienen de Dios, y que no son suyos?» (1 Cor. 6:19)",
    "«Han sido comprados por precio; por tanto, glorifiquen a Dios en su cuerpo.» (1 Cor. 6:20)",
    "«Ya han sido lavados, ya han sido santificados, ya han sido justificados en el nombre del Señor Jesucristo.» (1 Cor. 6:11)",
    "«No escribo esto para avergonzarlos, sino para amonestarlos como a hijos míos amados.» (1 Cor. 4:14)",
    "«Deben más bien perdonarlo y consolarlo, para que no sea consumido por la excesiva tristeza.» (2 Cor. 2:7)",
    "«Huyan de la inmoralidad sexual.» (1 Cor. 6:18)"
  ],
  "discussion": [
    "Muchos creyentes de Corinto querían la aprobación de la cultura que los rodeaba. ¿Dónde ves ese mismo deseo en nosotros hoy, y qué le hace a nuestra identidad como iglesia?",
    "En 1 Corintios 5 y 6 Pablo repite siete veces «¿no saben?» (1 Cor. 5:6; 6:2, 3, 9, 15, 16, 19), esperando un sí rotundo. ¿Qué cosas sabemos perfectamente y sin embargo vivimos como si no las supiéramos?",
    "La disciplina bíblica busca restaurar, no expulsar (1 Cor. 5:5; 2 Cor. 2:7). ¿Cómo evitamos los dos extremos: la dureza que humilla y el silencio que abandona?",
    "El matrimonio viene de Dios y debe ser honrado (Gén. 2:18-24; Heb. 13:4). En una época que lo considera anticuado, ¿cómo mostramos que es un regalo del Edén y no una regla heredada?"
  ],
  "facilitator": [
    {
      "stationId": "influencia",
      "apertura": "¿De dónde vienen, en realidad, las costumbres que damos por normales en la iglesia?",
      "seguimiento": "¿Qué influencia del entorno crees que más nos está formando sin que lo notemos?",
      "ilustracion": "La mente es una esponja: absorbe aunque no recuerdes, y luego devuelve lo absorbido en decisiones.",
      "transicion": "Si el entorno entra sin permiso, veamos qué terminamos tolerando sin darnos cuenta.",
      "actividad": "Que cada uno nombre en voz alta, si quiere, una sola influencia que quisiera filtrar esta semana.",
      "cierre": "Señor, cuida las puertas de nuestros sentidos y limpia lo que ya entró."
    },
    {
      "stationId": "tolerancia",
      "apertura": "Pablo se escandaliza dos veces en 1 Corintios 5: por el pecado y por el orgullo de tolerarlo. ¿Por qué lo segundo le duele tanto?",
      "seguimiento": "¿Qué conductas condenadas claramente en la Escritura corremos el peligro de tolerar en nombre del amor?",
      "ilustracion": "Una casa con una gotera tapada con un cuadro sigue teniendo gotera. Lo escondido no deja de mojar la pared.",
      "transicion": "Si hay algo que corregir, la pregunta siguiente es cómo se corrige sin destruir a nadie.",
      "actividad": "Lean 1 Corintios 5:1-2 y 1 Corintios 4:14 juntos y comparen el tono de Pablo en ambos.",
      "cierre": "Danos amor con ojos abiertos, Señor, y valor para nombrar lo que duele."
    },
    {
      "stationId": "restauracion",
      "apertura": "«A fin de que el espíritu sea salvo» (1 Cor. 5:5). ¿Cómo cambia esa frase la manera en que leemos todo el capítulo?",
      "seguimiento": "¿Cuándo se puede decir que la disciplina de la iglesia cumplió su propósito?",
      "ilustracion": "Un yeso aprieta e incomoda, pero existe para que el hueso vuelva a sostener. La disciplina bíblica es yeso, no condena.",
      "transicion": "De la restauración personal pasamos al conflicto entre hermanos y a cómo nos ve la ciudad.",
      "actividad": "Comparen 1 Corintios 5:5 con 2 Corintios 2:5-10 y sigan el recorrido del mismo hombre.",
      "cierre": "Enséñanos a corregir como tú corriges: firme, breve y con la mesa puesta."
    },
    {
      "stationId": "pleito",
      "apertura": "¿Por qué le molesta tanto a Pablo que dos creyentes lleven su pleito ante un tribunal civil?",
      "seguimiento": "¿Qué dice de nosotros el modo en que resolvemos nuestros conflictos internos?",
      "ilustracion": "En los tribunales romanos solía ganar el de más rango y más dinero. La iglesia debía juzgar con otro criterio.",
      "transicion": "Detrás del pleito y de la inmoralidad hay una misma pregunta: ¿de quién es este cuerpo y esta vida?",
      "actividad": "Lean 1 Corintios 6:1-8 y pregunten qué mesa concreta les falta en su congregación.",
      "cierre": "Haznos familia que se sienta a hablar antes que a acusar."
    },
    {
      "stationId": "pertenencia",
      "apertura": "¿Por qué Pablo enumera los pecados sexuales junto con la idolatría, el robo y la codicia (1 Cor. 6:9-10)?",
      "seguimiento": "¿Qué cambia en la práctica cuando alguien cree de verdad que su cuerpo es templo del Espíritu?",
      "ilustracion": "Tres verbos en pasado: lavados, santificados, justificados (1 Cor. 6:11). Dios ya actuó antes de pedirnos nada.",
      "transicion": "Si eso ya es verdad de nosotros, veamos el consejo más práctico de todos: huir.",
      "actividad": "Lean 1 Corintios 6:9-11 y subrayen el «ya» del versículo 11.",
      "cierre": "Gracias porque nos lavaste antes de que supiéramos pedirlo."
    },
    {
      "stationId": "huida",
      "apertura": "«Huyan» (1 Cor. 6:18) es un verbo raro para un apóstol valiente. ¿Por qué manda correr y no resistir?",
      "seguimiento": "¿Cómo podemos hablar de sexualidad en la iglesia con verdad y sin vergüenza?",
      "ilustracion": "José dejó su manto y salió corriendo (Gén. 39:12). Perdió una prenda y conservó una vida entera.",
      "transicion": "La fuerza para huir no sale de nosotros: sale de saber cuánto costamos.",
      "actividad": "Lean Génesis 39:6-18 y cuenten cuántas veces aparece la idea de huir.",
      "cierre": "Danos pies rápidos para lo que nos daña y corazón lento para juzgar a otros."
    },
    {
      "stationId": "precio",
      "apertura": "¿Qué cambia cuando alguien entiende que fue «comprado por precio» (1 Cor. 6:20)?",
      "seguimiento": "¿Cuál de estas verdades te cuesta más creer sobre ti mismo?",
      "ilustracion": "Nadie paga un precio alto por algo que no le importa. El precio revela el valor que Dios te da.",
      "transicion": "Ancladas en ese rescate, demos un paso concreto para los próximos días.",
      "actividad": "Reciten juntos 1 Corintios 6:19-20 y nombren el eslabón que más necesitan hoy.",
      "cierre": "Nos sostenemos en tu rescate, no en nuestro desempeño."
    },
    {
      "stationId": "paso",
      "apertura": "«El vacío es llenado por el Espíritu de Cristo.» ¿Qué hay que vaciar primero para que eso ocurra?",
      "seguimiento": "¿A quién podrías pedirle que camine contigo esta semana, sin que te juzgue?",
      "ilustracion": "Nadie sale de un pozo solo: alguien sostiene la cuerda arriba. Para eso existe la iglesia.",
      "transicion": "Cerremos con un paso concreto y un nombre al lado.",
      "actividad": "Compartan un solo paso para la semana y, si quieren, a quién van a invitar.",
      "cierre": "Llénanos de tu Espíritu y danos compañeros para el camino."
    }
  ],
  "patternTemplate": "{name}, empezaste nombrando lo que entraba sin permiso: {slot:influencia|lower|or:algo que no elegiste}. Reconociste que con lo que no está bien sueles {slot:tolerancia|lower|or:dejarlo pasar}, y aun así no te escondiste. Decidiste huir de {slot:huida|lower|or:lo que sabes que te daña} y sostenerte en {slot:precio|lower|or:lo que él pagó por ti}. El barro sigue siendo barro, pero ya tiene forma de templo.",
  "outOracion": "Señor, vengo tal como estoy. Reconozco que dejé entrar {slot:influencia|lower|or:cosas que nunca elegí} y que con lo que no está bien suelo {slot:tolerancia|lower|or:mirar para otro lado}. Hoy quiero dar un paso hacia la restauración: {slot:restauracion|or:volver a acercarme a quien me duele}. Con mi conflicto voy a dejar de {slot:pleito|lower|or:alimentarlo en silencio}, y voy a huir de {slot:huida|lower|or:lo que sé que me daña}. Enséñame a tratar mi cuerpo como {slot:pertenencia|lower|or:lo que es, tu templo}. Me sostengo en {slot:precio|lower|or:que fui comprado por precio}. Gracias porque «{verse}» ({verseRef}). En el nombre de Jesús, amén.",
  "outAliento": "{name}, nada de lo que nombraste hoy te descalifica. Pablo escribió aquellas páginas duras para restaurar, no para avergonzar, y esa sigue siendo la intención de Dios contigo. Vas a huir de {slot:huida|lower|or:lo que sabes que te daña} y a sostenerte en {slot:precio|lower|or:lo que él pagó por ti}, y no lo haces con tus fuerzas: lo haces porque ya fuiste comprado por precio y el Espíritu vive dentro de ti.",
  "outAccion24": "En las próximas 24 horas voy a {slot:paso|lower|or:dar un paso concreto hacia la restauración}, y voy a huir de {slot:huida|lower|or:lo que sé que me daña}.",
  "outPregunta": "Esta semana entendí que mi cuerpo es templo del Espíritu y que fui comprado por precio. Elegí sostenerme en {slot:precio|lower|or:que fui comprado por precio}. ¿Qué has aprendido a tolerar sin darte cuenta, y qué crees que cambiaría si de verdad te supieras rescatado?",
  "outTarjeta": "Mi templo de esta semana: reconocí que solía {slot:tolerancia|lower|or:mirar para otro lado}, decidí huir de {slot:huida|lower|or:lo que sé que me daña} y me sostengo en {slot:precio|lower|or:que fui comprado por precio}.\nVersículo: «{verse}» ({verseRef}).",
  "arc": "restore"
}
);
