import { makeLesson } from "../engine/makeLesson.js";

/* Lección 7 · Q3 2026 · 1 y 2 Corintios
   Authored from the official quarterly, then adapted for this engine.
   Generated by scripts/build-lessons.mjs. Edit the draft, not this file. */
export default makeLesson(
{
  "number": 7,
  "slug": "retrato-del-amor",
  "title": "Un Retrato del Amor",
  "subtitle": "¿Y si este capítulo no fuera un poema de bodas, sino un espejo?",
  "kitName": "Mi Retrato del Amor",
  "artifactNoun": "retrato",
  "motif": "retrato",
  "stages": [
    "lienzo",
    "carbon",
    "sombras",
    "color",
    "luz"
  ],
  "stageLabels": [
    "Lienzo en blanco · el amor se enfrió",
    "Primer trazo · me miro sin adornos",
    "Sombras al descubierto · lo que no hago",
    "Entra el color · el rostro de Jesús",
    "Retrato a plena luz · el mayor es el amor"
  ],
  "verseRef": "1 Cor. 13:13",
  "verseText": "Ahora permanecen estos tres dones: la fe, la esperanza y el amor. Pero el mayor es el amor.",
  "promise": "En unos minutos vas a pintar tu Retrato, {name}: te pondrás delante del espejo más honesto del Nuevo Testamento, nombrarás el verbo del amor que menos practicas, mirarás el rostro de Jesús en cada rasgo y elegirás a una persona concreta con quien empezar esta semana. Trazo a trazo, lo que hoy es un lienzo frío va a tomar color.",
  "ui": {
    "start": "Empezar mi retrato",
    "emptyKit": "Tu retrato",
    "building": "Cada respuesta añade un trazo",
    "buildingHint": "Toca la pieza que brilla. Verás el lienzo pasar del carbón al color.",
    "lastPiece": "Falta un trazo",
    "patternLabel": "Tu patrón en el retrato",
    "doneTitle": "Tu retrato está terminado",
    "doneSub": "Lo pintaste tú, con él. Ábrelo, guárdalo, compártelo.",
    "open": "Abrir mi retrato",
    "back": "Volver a mi retrato",
    "kitName": "Mi Retrato del Amor"
  },
  "slots": [
    {
      "id": "espejo",
      "n": 1,
      "label": "Mi espejo honesto",
      "teaser": "Lo que el capítulo me devuelve hoy…",
      "icon": "eye"
    },
    {
      "id": "esencia",
      "n": 2,
      "label": "Lo que sin amor no vale nada",
      "teaser": "Aquello bueno mío que puede sonar a metal…",
      "icon": "gift"
    },
    {
      "id": "verbo",
      "n": 3,
      "label": "El verbo que me falta",
      "teaser": "Lo que el amor hace y yo todavía no…",
      "icon": "hand"
    },
    {
      "id": "sombra",
      "n": 4,
      "label": "La sombra que suelto",
      "teaser": "Lo que el amor no hace y yo sí…",
      "icon": "flame"
    },
    {
      "id": "rostro",
      "n": 5,
      "label": "El rostro que copio",
      "teaser": "La verdad que sostengo sobre Jesús…",
      "icon": "cross"
    },
    {
      "id": "tres",
      "n": 6,
      "label": "Lo que permanece",
      "teaser": "Lo único que no va a caducar…",
      "icon": "anchor"
    },
    {
      "id": "fuente",
      "n": 7,
      "label": "La fuente",
      "teaser": "Por qué «Dios es amor» es buena noticia…",
      "icon": "heart"
    },
    {
      "id": "paso",
      "n": 8,
      "label": "Mi verbo y mi nombre",
      "teaser": "Un verbo concreto y una persona real…",
      "icon": "people"
    }
  ],
  "stations": [
    {
      "id": "espejo",
      "day": "Sábado · Un retrato del amor",
      "tag": "Trazo 1 · Mi espejo honesto",
      "title": "No es un poema de bodas",
      "story": "Has oído 1 Corintios 13 leído entre flores y anillos. Pablo no lo escribió para una boda. Lo escribió para una iglesia que se llevaba a juicio unos a otros, que se dividía en bandos y que humillaba a los pobres en la mesa del Señor. Cuando escribe «el amor es paciente», está señalando con el dedo. Antes de ser tu consuelo, este capítulo es tu espejo.",
      "cue": "Antes de leerlo como poesía, {name}, léelo como espejo.",
      "module": {
        "type": "choiceInsight",
        "privacy": true,
        "prompt": "Cuando lees 1 Corintios 13 con honestidad, ¿qué sientes primero?",
        "hint": "Elige la reacción más sincera, no la más piadosa",
        "saveLabel": "Guardar en mi retrato",
        "seedSub": "tu espejo",
        "closing": "Que te incomode es buena señal: para eso lo escribió Pablo. Pero el espejo no se te da para hundirte. «El amor de Dios ha sido derramado en nuestros corazones por el Espíritu Santo» (Rom. 5:5). Lo que ves que te falta, él lo da.",
        "options": [
          {
            "id": "ternura",
            "label": "Ternura, porque me recuerda que soy amado",
            "insight": "Está bien empezar ahí. Solo no te quedes: el mismo capítulo que te abraza te va a pedir cuentas de a quién estás amando así.",
            "tags": [
              "theme:love",
              "posture:humble",
              "tone:tender"
            ]
          },
          {
            "id": "condena",
            "label": "Condena, porque no doy la talla en casi nada",
            "insight": "Nadie da la talla. Pablo tampoco. Por eso escribió que Cristo mostró en él «su paciencia infinita» (1 Tim. 1:16). El retrato no es una vara para golpearte, es un rostro que se te ofrece.",
            "tags": [
              "react:fear",
              "theme:grace",
              "tone:raw"
            ]
          },
          {
            "id": "incomodidad",
            "label": "Incomodidad, porque describe justo lo que no soy",
            "insight": "Esa incomodidad es honestidad, y la honestidad es el primer trazo del retrato. Lo que niegas no se puede pintar de nuevo.",
            "tags": [
              "theme:self",
              "posture:humble",
              "tone:raw"
            ]
          },
          {
            "id": "costumbre",
            "label": "Costumbre, lo he oído tantas veces que ya no me toca",
            "insight": "Un texto memorizado puede volverse un texto anestesiado. Prueba a leerlo hoy pensando en la persona con la que peor te llevas, y verás cómo despierta.",
            "tags": [
              "react:apathy",
              "theme:word",
              "posture:avoidant"
            ]
          },
          {
            "id": "defensa",
            "label": "Defensa, pienso en quién debería leerlo y no en mí",
            "insight": "Los corintios hicieron exactamente eso. Pablo escribió «el amor no se envanece» (1 Cor. 13:4) a gente convencida de que el problema era el otro bando.",
            "tags": [
              "react:pride",
              "theme:humility",
              "posture:proud"
            ]
          },
          {
            "id": "frialdad",
            "label": "Frialdad, mi amor se enfrió y lo sé",
            "insight": "Jesús avisó de esto: «el amor de muchos se enfriará» (Mat. 24:12). Que lo reconozcas significa que todavía te importa. El fuego que se apagó puede volver a encenderse.",
            "tags": [
              "react:withdraw",
              "theme:love",
              "tone:raw"
            ]
          },
          {
            "id": "hambre",
            "label": "Hambre, quiero amar así y no sé por dónde empezar",
            "insight": "Empieza por una persona y un verbo. El amor de este capítulo no se conquista entero: se practica en concreto, con alguien que tiene nombre.",
            "tags": [
              "theme:love",
              "posture:seeking",
              "tone:tender"
            ]
          }
        ]
      }
    },
    {
      "id": "esencia",
      "day": "Domingo · La esencialidad del amor",
      "tag": "Trazo 2 · Lo que sin amor no vale nada",
      "title": "Metal que resuena",
      "story": "Pablo hace una resta brutal. Lenguas, profecía, conocimiento, fe que mueve montañas, repartir todos tus bienes, hasta entregar tu cuerpo. Quítale el amor y el resultado es cero. No dice que esas cosas sean malas; dice que sin amor no son nada. Y el amor del que habla no es un sentimiento que te llega de pronto, sino la gracia del Espíritu que te empuja a actuar en favor de otro.",
      "cue": "Haz la resta contigo, {name}, y mira qué queda.",
      "module": {
        "type": "choiceInsight",
        "privacy": false,
        "prompt": "¿Qué cosa buena tuya corre el riesgo de sonar a metal que resuena?",
        "hint": "Algo que haces bien, pero a veces sin amor",
        "saveLabel": "Guardar en mi retrato",
        "seedSub": "tu resta",
        "closing": "«El conocimiento envanece, pero el amor edifica» (1 Cor. 8:1). Ninguna de estas cosas es mala. Solo son cero cuando se hacen sin amor, y el frío casi siempre empieza por aquello que mejor te sale.",
        "options": [
          {
            "id": "conocimiento",
            "label": "Lo que sé de la Biblia",
            "insight": "Corinto estaba lleno de gente que sabía. Saber más que otro sin amarlo más que otro es la definición exacta de envanecerse (1 Cor. 8:1).",
            "tags": [
              "react:pride",
              "theme:word",
              "posture:proud"
            ]
          },
          {
            "id": "servicio",
            "label": "Todo lo que hago en la iglesia",
            "insight": "Se puede sostener un ministerio entero por inercia, por deber o por miedo al vacío. Pregúntate por quién lo haces, no cuánto haces.",
            "tags": [
              "react:apathy",
              "theme:service",
              "tone:raw"
            ]
          },
          {
            "id": "generosidad",
            "label": "Lo que doy y lo que ayudo",
            "insight": "Pablo llega a decir que repartir todos los bienes sin amor no sirve de nada (1 Cor. 13:3). La mano puede dar mientras el corazón cobra reconocimiento.",
            "tags": [
              "theme:generosity",
              "posture:proud",
              "tone:resolute"
            ]
          },
          {
            "id": "firmeza",
            "label": "Mi firmeza para señalar lo correcto",
            "insight": "Tener razón no es un valor cristiano por sí solo. En Corinto, los «fuertes» tenían razón y aun así herían a los débiles (1 Cor. 8).",
            "tags": [
              "react:control",
              "theme:truth",
              "posture:proud"
            ]
          },
          {
            "id": "sacrificio",
            "label": "Lo mucho que aguanto por los míos",
            "insight": "Aguantar sin amar produce mártires amargados. Si tu sacrificio se convierte en una factura que pasas a los demás, ya no es amor.",
            "tags": [
              "theme:relationship",
              "react:control",
              "tone:raw"
            ]
          },
          {
            "id": "oracion",
            "label": "Mi disciplina espiritual",
            "insight": "Una vida devocional impecable que no cambia cómo tratas a la persona difícil es un címbalo bien afinado. Suena fuerte y no dice nada.",
            "tags": [
              "theme:prayer",
              "posture:clinging",
              "tone:resolute"
            ]
          }
        ]
      }
    },
    {
      "id": "verbo",
      "day": "Lunes · Lo que el amor hace",
      "tag": "Trazo 3 · El verbo que me falta",
      "title": "El amor se conjuga",
      "story": "Pablo no define el amor: lo conjuga. Es paciente. Es bondadoso. Se alegra con la verdad. Todo lo sufre, todo lo cree, todo lo espera, todo lo soporta. Ni un solo adjetivo sobre lo que el amor siente; solo verbos sobre lo que el amor hace, y casi siempre hacia alguien difícil. Si el amor fuera una emoción, dependería de tu humor. Como es un verbo, puedes empezar hoy.",
      "cue": "{name}, elige un verbo, no una buena intención.",
      "module": {
        "type": "pickReveal",
        "saveLabel": "Guardar en mi retrato",
        "seedSub": "tu verbo",
        "prompt": "¿Cuál de estos verbos del amor es el que más te falta?",
        "hint": "Toca cada uno y quédate con el que más te acusa",
        "chooseLabel": "Este es el verbo que voy a practicar",
        "closing": "Ese verbo no lo vas a fabricar apretando los dientes. Es «fruto del Espíritu» (Gál. 5:22), y el fruto solo aparece en la rama que permanece unida.",
        "allowCustom": {
          "label": "Escribir el mío",
          "placeholder": "El verbo que más me falta es…",
          "extraKey": "verboPropio"
        },
        "items": [
          {
            "t": "Es paciente, aguanta a la persona que me agota",
            "ref": "1 Cor. 13:4",
            "meaning": "Makrothymeō es paciencia larga con personas, no con el tráfico. Pablo la une a «soportándoos con paciencia los unos a los otros en amor» (Efe. 4:2)."
          },
          {
            "t": "Es bondadoso, trato a otros como Dios me trata",
            "ref": "1 Cor. 13:4",
            "meaning": "El verbo evoca la bondad de Dios en los Salmos: «Bueno es Jehová para con todos» (Sal. 145:9). Tu bondad no se mide por tu carácter, sino por la suya."
          },
          {
            "t": "Todo lo cree, doy el beneficio de la duda",
            "ref": "1 Cor. 13:7",
            "meaning": "No es ingenuidad, es negarse a asumir lo peor del otro. Jesús llamó a Saulo «instrumento escogido» (Hech. 9:15) cuando todos veían a un perseguidor."
          },
          {
            "t": "Todo lo soporta, no me rindo con quien me falló",
            "ref": "1 Cor. 13:7",
            "meaning": "Stegō es cubrir y resistir; hypomenō es perseverar. El amor ni publica la caída del otro ni lo abandona a mitad de camino."
          }
        ]
      }
    },
    {
      "id": "sombra",
      "day": "Martes · Lo que el amor no hace",
      "tag": "Trazo 4 · La sombra que suelto",
      "title": "La lista, leída al revés",
      "story": "Un comentarista notó algo incómodo: si le quitas el «no» a las ocho cosas que el amor no hace, obtienes un retrato bastante exacto de los corintios. Envidiosos, jactanciosos, envanecidos, groseros, egoístas, irascibles y muy atentos a los errores ajenos. Pablo eligió esos verbos porque los había visto funcionando en esa iglesia. Léelos despacio y entenderás por qué la lista sigue vigente.",
      "cue": "Sostén la mirada un momento, {name}. La lista también te nombra.",
      "module": {
        "type": "skillThenCommit",
        "saveLabel": "Guardar en mi retrato",
        "seedSub": "tu sombra",
        "skill": {
          "prompt": "¿Esto es amor, o es Corinto disfrazado de amor?",
          "hint": "Seis escenas corrientes. Clasifícalas sin piedad.",
          "badge": "Estás aprendiendo a reconocer el amor que no lleva cuentas",
          "cats": [
            "Esto es amor",
            "Esto es Corinto"
          ],
          "rounds": [
            {
              "t": "«Ya lo perdoné, pero de vez en cuando se lo recuerdo.»",
              "a": 1,
              "fb": "Corinto. Logizomai era un verbo de contabilidad: el amor no anota las ofensas en ninguna columna (1 Cor. 13:5)."
            },
            {
              "t": "«Me alegré de verdad cuando a mi compañero le fue mejor que a mí.»",
              "a": 0,
              "fb": "Amor. Synjairō es alegrarse junto a otro, lo contrario exacto de la envidia que dividía Corinto (1 Cor. 13:4)."
            },
            {
              "t": "«Conté su caída en el grupo, en tono de petición de oración.»",
              "a": 1,
              "fb": "Corinto. El amor no se goza de la injusticia y cubre en lugar de divulgar (1 Cor. 13:6-7)."
            },
            {
              "t": "«Renuncié a un derecho mío para no herir a un hermano.»",
              "a": 0,
              "fb": "Amor. «Ninguno busque su propio bien, sino el de los demás» (1 Cor. 10:24). Ahí se cae toda la lista negativa de golpe."
            },
            {
              "t": "«Tengo razón y pienso decirla, aunque lo deje por el suelo.»",
              "a": 1,
              "fb": "Corinto. «El conocimiento envanece, pero el amor edifica» (1 Cor. 8:1). Tener razón sin amor sigue siendo nada."
            },
            {
              "t": "«Respondí con calma a quien me contestó mal.»",
              "a": 0,
              "fb": "Amor. Paroxynō es encenderse enseguida. El amor no es susceptible ni cobra la ofensa en el momento (1 Cor. 13:5)."
            }
          ],
          "summary": "Las ocho negaciones caben en una sola frase: el amor no busca lo suyo. Ahí se caen la envidia, la jactancia, la grosería y el rencor. Corinto no era una iglesia sin dones, era una iglesia sin esa frase."
        },
        "commit": {
          "prompt": "¿Cuál de estas sombras vas a soltar esta semana?",
          "hint": "Nombrarla en voz alta ya es empezar a soltarla",
          "placeholder": "la sombra que voy a soltar es…",
          "extraKey": "sombraTexto",
          "options": [
            "Llevar la cuenta de una ofensa",
            "Envidiar lo que otro recibió",
            "Necesitar tener siempre la razón",
            "Irritarme a la primera",
            "Comentar la falta de alguien"
          ]
        }
      }
    },
    {
      "id": "rostro",
      "day": "Miércoles · Un retrato de Jesús",
      "tag": "Trazo 5 · El rostro que copio",
      "title": "Pon su nombre en el texto",
      "story": "Haz la prueba. Donde el capítulo dice «el amor», lee «Jesús». Jesús es paciente. Jesús es bondadoso. Jesús no busca lo suyo. Jesús todo lo soporta. Cada línea encaja sin forzar nada, porque el retrato del amor es, en el fondo, un retrato de él. Ahora pon tu propio nombre y entenderás por qué necesitas gracia y no solo esfuerzo.",
      "cue": "{name}, mira el retrato terminado antes de mirar el tuyo.",
      "module": {
        "type": "perspectiveFlip",
        "saveLabel": "Guardar en mi retrato",
        "seedSub": "tu rostro",
        "prompt": "Toca cada carta: lo que ves en ti, y lo que él ve",
        "hint": "Dos miradas sobre el mismo lienzo",
        "pairs": [
          {
            "see": "Ves tu lista de fracasos en amar.",
            "sees": "Él «soportó la cruz» por ti «en vista del gozo que le esperaba» (Heb. 12:2). Ese gozo eras tú."
          },
          {
            "see": "Ves a alguien que se irrita y lleva cuentas.",
            "sees": "«Cristo Jesús mostró en mí su paciencia infinita» (1 Tim. 1:16). Lo que recibió Pablo, el peor de los pecadores, no fue una lista sino misericordia."
          },
          {
            "see": "Ves a la persona difícil tal como es hoy.",
            "sees": "Jesús vio en Saulo un «instrumento escogido» (Hech. 9:15) cuando aún respiraba amenazas. Así te ve a ti, y así puedes ver tú."
          },
          {
            "see": "Ves que amar así te queda enorme.",
            "sees": "«El amor es de Dios» (1 Juan 4:7). No se te pide producirlo, se te invita a recibirlo y dejar que pase por ti."
          }
        ],
        "chooseLabel": "Esta es la verdad que sostengo",
        "teach": "Nunca vas a amar como él a fuerza de intentarlo. Este amor es una gracia que concede el Espíritu, no un músculo que se entrena a solas. Se contempla el rostro de Jesús hasta que uno empieza a parecérsele.",
        "commit": {
          "prompt": "Escribe una frase de aliento para alguien que necesita ver ese rostro en ti",
          "hint": "Una sola frase. Puedes enviarla hoy mismo.",
          "placeholder": "Quiero decirte que…",
          "extraKey": "alientoEscrito",
          "shareable": true
        }
      }
    },
    {
      "id": "tres",
      "day": "Jueves · Fe, esperanza y amor",
      "tag": "Trazo 6 · Lo que permanece",
      "title": "Lo que sobrevive al final",
      "story": "Un día ya no harán falta las profecías. Las lenguas callarán. El conocimiento a medias dará paso a ver «cara a cara» (1 Cor. 13:12). Casi todo lo que hoy te parece imprescindible, incluso los dones por los que Corinto se peleaba, tiene fecha de caducidad. Tres cosas permanecen: la fe, la esperanza y el amor. Y el mayor es el amor, porque es lo único de la lista que describe lo que Dios es.",
      "cue": "{name}, quédate esta semana con lo que no va a caducar.",
      "module": {
        "type": "anchorChain",
        "saveLabel": "Echar el ancla y guardar",
        "seedSub": "lo que permanece",
        "chain": [
          {
            "word": "Los dones cesarán",
            "line": "No porque fueran malos, sino porque habrán cumplido aquello para lo que existían (1 Cor. 13:10)."
          },
          {
            "word": "La fe permanece",
            "line": "Hoy andamos por fe y no por vista (2 Cor. 5:7). Aun cuando lo veas, seguirás confiando en él para siempre."
          },
          {
            "word": "La esperanza permanece",
            "line": "Lo que esperas se hará realidad (Rom. 8:24), y en la tierra nueva seguirás esperando cosas buenas de sus manos."
          },
          {
            "word": "El amor es el mayor",
            "line": "«Dios es amor» (1 Juan 4:8). Es la única de las tres que se usa para describir lo que él es, no solo lo que tú haces."
          }
        ],
        "climax": "«Ahora permanecen estos tres dones: la fe, la esperanza y el amor. Pero el mayor es el amor» (1 Cor. 13:13). Echa el ancla aquí.",
        "prompt": "¿Cuál de estas verdades vas a sostener esta semana?",
        "hint": "Cuando amar te salga caro, vuelve a la que elijas",
        "options": [
          "Que el amor nunca deja de ser",
          "Que Dios es amor y no cambia de humor",
          "Que un día lo veré cara a cara",
          "Que lo hecho con amor no se pierde",
          "Que mi fe y mi esperanza no fueron en vano"
        ],
        "allowCustom": {
          "placeholder": "la verdad que sostengo es…",
          "extraKey": "verdadPropia"
        }
      }
    },
    {
      "id": "fuente",
      "day": "El amor que llegó primero",
      "tag": "Trazo 7 · La fuente",
      "title": "Antes de mandarte amar, te amó",
      "story": "Ninguno de los quince verbos de este capítulo empezó en ti. «Nosotros le amamos a él, porque él nos amó primero» (1 Juan 4:19). Por eso el retrato no es una vara para medirte y condenarte, sino un rostro que se te ofrece. Antes de pedirte paciencia, él fue infinitamente paciente contigo. Antes de pedirte que no lleves cuentas, borró la tuya en la cruz.",
      "cue": "Respira, {name}. Esta parte no depende de tu esfuerzo.",
      "module": {
        "type": "choiceInsight",
        "privacy": false,
        "prompt": "«Dios es amor». ¿Qué parte de esa frase necesitas hoy?",
        "hint": "Elige la que más falta te hace ahora mismo",
        "saveLabel": "Guardar en mi retrato",
        "seedSub": "tu fuente",
        "closing": "«En esto consiste el amor: no en que nosotros hayamos amado a Dios, sino en que él nos amó a nosotros» (1 Juan 4:10). Todo lo que puedas dar esta semana, primero lo recibiste.",
        "options": [
          {
            "id": "primero",
            "label": "Que me amó primero, sin que yo hiciera nada",
            "insight": "Su amor no fue una respuesta a tus méritos: fue la iniciativa que hizo posible todo lo demás. Nada de lo que hagas hoy inició esta historia.",
            "tags": [
              "theme:grace",
              "posture:surrendering",
              "tone:tender"
            ]
          },
          {
            "id": "paciente",
            "label": "Que ha sido infinitamente paciente conmigo",
            "insight": "Pablo se llamó «el peor de los pecadores» y dijo que en él Cristo mostró «su paciencia infinita» (1 Tim. 1:16). Si te aguantó a ti, puede enseñarte a aguantar a otro.",
            "tags": [
              "theme:grace",
              "posture:humble",
              "tone:raw"
            ]
          },
          {
            "id": "cuentas",
            "label": "Que no lleva la cuenta de mis ofensas",
            "insight": "El mismo verbo contable que Pablo usa en 1 Corintios 13:5 aparece en Romanos 4:8: «Bienaventurado el varón a quien el Señor no culpa de pecado». Tu columna está en blanco.",
            "tags": [
              "theme:cross",
              "theme:sin",
              "posture:humble"
            ]
          },
          {
            "id": "espera",
            "label": "Que me ve como llegaré a ser, no como soy",
            "insight": "Es lo que hizo con Saulo, con Pedro y con cada uno de los corintios que se peleaban. Ve el retrato terminado mientras tú solo ves el carbón.",
            "tags": [
              "theme:hope",
              "posture:seeking",
              "tone:tender"
            ]
          },
          {
            "id": "constante",
            "label": "Que su amor no se enfría cuando el mío sí",
            "insight": "Jesús advirtió que el amor de muchos se enfriaría (Mat. 24:12). Nunca dijo que el suyo lo hiciera. Tu temperatura cambia; la fuente no.",
            "tags": [
              "react:doubt",
              "theme:faith",
              "tone:raw"
            ]
          },
          {
            "id": "cruz",
            "label": "Que la cruz es la medida de cuánto me ama",
            "insight": "No tienes que imaginar cuánto vales para él: hay una cifra clavada en un madero. «En esto hemos conocido el amor, en que él puso su vida por nosotros» (1 Juan 3:16).",
            "tags": [
              "theme:cross",
              "theme:love",
              "tone:resolute"
            ]
          }
        ]
      }
    },
    {
      "id": "paso",
      "day": "Viernes · Para estudiar y meditar",
      "tag": "Trazo 8 · Mi verbo y mi nombre",
      "title": "Un verbo y un nombre",
      "story": "Elena G. de White escribió que «únicamente el amor que haya fluido del corazón de Cristo puede proporcionar sanidad» (La educación, p. 102). Ese amor no se derrama sobre la humanidad en abstracto: se derrama sobre alguien que tiene nombre. Pablo no pidió a los corintios que amaran más en general; les pidió que dejaran de llevarse a juicio, de envidiarse y de humillar al hermano que tenían al lado. Tu retrato queda incompleto hasta que aparece una persona en él.",
      "cue": "{name}, escribe un nombre. El amor sin nombre todavía no es amor.",
      "module": {
        "type": "commitDuo",
        "saveLabel": "Cerrar mi retrato",
        "seedSub": "tu paso",
        "stepPrompt": "El verbo del amor que voy a practicar esta semana",
        "stepHint": "Pequeño y concreto. Toca una idea o escribe la tuya.",
        "stepOptions": [
          "Ser paciente sin suspirar ni interrumpir",
          "Responder con bondad a quien me hable mal",
          "No comentar la falta de nadie",
          "Dar el beneficio de la duda antes de juzgar",
          "Ceder un derecho mío para no herir"
        ],
        "stepPlaceholder": "esta semana voy a…",
        "stepExtraKey": "verboPracticado",
        "personPrompt": "La persona con quien lo voy a practicar",
        "personHint": "La difícil. Esa en la que acabas de pensar.",
        "personPlaceholder": "un nombre…",
        "personExtraKey": "personaAmada"
      }
    }
  ],
  "encourage": [
    "«Ahora permanecen estos tres dones: la fe, la esperanza y el amor. Pero el mayor es el amor.» (1 Cor. 13:13)",
    "«El amor es sufrido, es benigno; el amor no tiene envidia, no es jactancioso, no se envanece.» (1 Cor. 13:4)",
    "«No busca lo suyo, no se irrita, no guarda rencor.» (1 Cor. 13:5)",
    "«El amor nunca deja de ser.» (1 Cor. 13:8)",
    "«Por haberse multiplicado la maldad, el amor de muchos se enfriará.» (Mat. 24:12)",
    "«Nosotros le amamos a él, porque él nos amó primero.» (1 Juan 4:19)"
  ],
  "discussion": [
    "La lista de características del amor en 1 Corintios 13 no pretende ser exhaustiva. Si Pablo escribiera hoy a tu congregación, ¿qué rasgo añadiría, y por qué precisamente ese?",
    "Pablo manda «seguid el amor» (1 Cor. 14:1), como quien persigue algo que se le escapa. ¿Qué diferencia hay entre sentir amor y perseguirlo? ¿Cómo se ve esa persecución un martes cualquiera?",
    "Si le quitamos el «no» a las ocho cosas que el amor no hace, aparece el retrato de Corinto. Con valentía y sin señalar a nadie: ¿cuál de esas ocho se nota más hoy en nuestra iglesia?",
    "Pablo presenta el amor como la solución definitiva a las divisiones de Corinto, no la reorganización ni la doctrina. ¿Por qué? ¿Qué conflicto concreto de nuestra iglesia se resolvería si durante una semana nadie buscara lo suyo?"
  ],
  "facilitator": [
    {
      "stationId": "espejo",
      "apertura": "¿Dónde han escuchado leer 1 Corintios 13? ¿Cambia algo saber que se escribió para una iglesia que se llevaba a juicio unos a otros?",
      "seguimiento": "Cuando lo leen despacio, ¿les consuela o les incomoda? Sean honestos.",
      "ilustracion": "Un espejo no odia a quien se mira en él. Solo se niega a mentirle.",
      "transicion": "Si el capítulo es un espejo, empecemos por la resta que hace Pablo: quita el amor y mira qué queda.",
      "actividad": "Lean 1 Corintios 13:1-3 en voz alta, despacio, y guarden diez segundos de silencio antes de comentar.",
      "cierre": "Señor, danos valor para mirarnos en tu espejo sin apartar la vista."
    },
    {
      "stationId": "esencia",
      "apertura": "Pablo dice que sin amor no somos nada, aunque tengamos fe para mover montañas. ¿Por qué es tan duro?",
      "seguimiento": "¿Qué cosa buena hacemos en esta iglesia que podría estar sonando a metal?",
      "ilustracion": "Un címbalo suena fortísimo y no comunica nada. Volumen sin mensaje.",
      "transicion": "Si el amor es lo que da valor a todo lo demás, veamos qué hace exactamente el amor.",
      "actividad": "Hagan la resta en voz alta: nombren un don o un servicio y pregunten qué queda si se le quita el amor.",
      "cierre": "Guárdanos, Señor, de servirte con las manos llenas y el corazón frío."
    },
    {
      "stationId": "verbo",
      "apertura": "Pablo describe el amor con verbos y no con adjetivos. ¿Qué cambia esa decisión para nuestra vida diaria?",
      "seguimiento": "¿Cuál de los siete verbos positivos les resulta más difícil, y con qué tipo de persona?",
      "ilustracion": "Makrothymeō es paciencia larga con personas, no con el tráfico. Es aguantar a alguien, no algo.",
      "transicion": "Vista la lista de lo que el amor hace, miremos la lista incómoda de lo que el amor no hace.",
      "actividad": "Repartan los siete verbos de 1 Corintios 13:4-7 y que cada uno dé un ejemplo concreto de esta semana.",
      "cierre": "Enséñanos, Señor, a conjugar el amor y no solo a definirlo."
    },
    {
      "stationId": "sombra",
      "apertura": "Si quitamos el «no» a las ocho características negativas, obtenemos el retrato de Corinto. ¿Y el nuestro?",
      "seguimiento": "Logizomai era un término de contabilidad. ¿Qué cuentas seguimos guardando?",
      "ilustracion": "Perdonar sin cerrar la cuenta es como romper la factura y quedarse con una fotocopia.",
      "transicion": "Ninguno cumple la lista completa. Por eso hay que mirar al único que sí la cumplió.",
      "actividad": "Lean 1 Corintios 13:4-6 quitando cada «no» y comenten cuál de las ocho duele más.",
      "cierre": "Perdónanos, Señor, las cuentas que hemos guardado contra tus hijos."
    },
    {
      "stationId": "rostro",
      "apertura": "Lean 1 Corintios 13:4-7 cambiando «el amor» por «Jesús». ¿Qué notan?",
      "seguimiento": "Ahora pongan su propio nombre en el texto. ¿Qué sienten, y qué van a hacer con eso?",
      "ilustracion": "Ananías veía a un perseguidor; Jesús veía un instrumento escogido (Hech. 9:13-15). Mismo hombre, dos miradas.",
      "transicion": "Si él es el retrato, veamos ahora lo único que permanece: fe, esperanza y amor.",
      "actividad": "Cada persona escribe una frase de aliento para alguien de la clase y se la entrega antes de terminar.",
      "cierre": "Cristo, imprime tu rostro en nosotros hasta que se nos note."
    },
    {
      "stationId": "tres",
      "apertura": "Un día cesarán los dones y el conocimiento parcial. ¿Qué dice eso sobre las cosas que hoy nos dividen?",
      "seguimiento": "¿Por qué el amor es mayor que la fe y la esperanza?",
      "ilustracion": "El amor es la única de las tres que se usa para describir lo que Dios es, no solo lo que hacemos nosotros (1 Juan 4:8).",
      "transicion": "Y ese amor eterno no empezó en nosotros. Vayamos a la fuente.",
      "actividad": "Lean 1 Corintios 13:8-13 y hagan dos columnas: lo que caduca y lo que permanece.",
      "cierre": "Ánclanos, Señor, en lo único que no va a caducar."
    },
    {
      "stationId": "fuente",
      "apertura": "«Dios es amor» (1 Juan 4:8). ¿Qué significa exactamente, y por qué es una buena noticia?",
      "seguimiento": "¿En qué cambia tu semana saber que él te amó primero?",
      "ilustracion": "La cruz no mide cuánto debemos amar, sino cuánto ya fuimos amados.",
      "transicion": "Recibido el amor, toca darlo, y darlo con nombre propio.",
      "actividad": "Lean 1 Juan 4:7-12 y que cada uno nombre una manera concreta en que Dios lo amó primero.",
      "cierre": "Gracias, Padre, porque tu amor no espera a que seamos amables."
    },
    {
      "stationId": "paso",
      "apertura": "Elena G. de White dice que solo el amor que fluye del corazón de Cristo puede sanar. ¿Por qué solo ese?",
      "seguimiento": "¿A quién le toca recibirlo de ti esta semana? Piensa en un nombre, no en un grupo.",
      "ilustracion": "Pablo no pidió a los corintios amar más en general; les pidió dejar de llevarse a juicio unos a otros.",
      "transicion": "Cerremos el retrato con lo único que lo completa: un verbo y un nombre.",
      "actividad": "Que cada uno diga en voz alta el verbo que practicará y, si quiere, solo la inicial de la persona.",
      "cierre": "Danos, Señor, amor con nombre propio y manos que lo demuestren."
    }
  ],
  "patternTemplate": "{name}, te miraste en el espejo del capítulo y lo primero que sentiste fue {slot:espejo|lower}. Reconociste que {slot:esencia|lower} puede sonar a metal si va sin amor, elegiste practicar un verbo ({slot:verbo|lower}) y soltar la costumbre de {slot:sombra|lower}. El lienzo ya no está en blanco: donde había carbón empieza a entrar color, porque el rostro que estás copiando es el suyo.",
  "outOracion": "Señor, me puse delante de tu espejo y lo primero que sentí fue {slot:espejo|lower}. Reconozco que {slot:esencia|lower} se me puede volver ruido si lo hago sin amor. Enséñame el verbo que me falta: {slot:verbo|lower}. Quítame la sombra de {slot:sombra|lower}. Que la verdad que sostengo sea esta: {slot:rostro} Me anclo en {slot:tres|lower}, y recibo de ti que {slot:fuente|lower}. Dame amor concreto para {slot:paso|lower}, esta semana, con una persona de nombre y apellido. Gracias porque «{verse}» ({verseRef}). En el nombre de Jesús, amén.",
  "outAliento": "{name}, este capítulo te dejó sin excusas, y eso está bien: es exactamente lo que Pablo quería. Pero no te deja solo. El que te pide paciencia fue infinitamente paciente contigo, y el que te pide no llevar cuentas ya borró la tuya. Elegiste practicar {slot:verbo|lower} y soltar {slot:sombra|lower}. No lo vas a lograr apretando los dientes: lo vas a recibir. «El amor es de Dios» (1 Juan 4:7), y él tiene de sobra.",
  "outAccion24": "En las próximas 24 horas voy a {slot:paso|lower}, y lo haré con la persona que anoté, no con la humanidad en general.",
  "outPregunta": "Esta semana leí 1 Corintios 13 como espejo y no como poema de bodas, y descubrí que me falta esto: {slot:verbo|lower}. ¿Qué verbo del amor te falta a ti, y con quién lo practicarías esta semana?",
  "outTarjeta": "Mi retrato de esta semana: dejé de leer 1 Corintios 13 como poema, elegí practicar {slot:verbo|lower} y soltar {slot:sombra|lower}.\nVersículo: «{verse}» ({verseRef})."
}
);
